In [1]:
import pandas as pd
import numpy 
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt

In [2]:
d = pd.DataFrame.from_csv('partial_datacsv.csv', index_col=None)
d.head()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2802: DtypeWarning: Columns (5,205,206,256) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

,patient_id,encounter_id,time,loc_cat,unit1,unit2,IVF_meds,IVF_volume,IV_intake,avpu,...,gcs_score_sofa,creatinine_sofa,sofa_resp,sofa_coag,sofa_bili,sofa_card,sofa_gcs,sofa_cr,sofa_score,immuno_group
0,155043,155164,25apr2013 22:36:00,WARD,T3SW,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
1,155043,155164,26apr2013 17:00:00,WARD,TS356 (room 117),NaN,NaN,100.0,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
2,155043,155164,26apr2013 05:18:00,WARD,TS356 (room 117),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
3,155043,155164,26apr2013 14:32:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
4,155043,155164,26apr2013 02:49:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0

In [ ]:
d.describe()

In [3]:
d_final = d[d["infxnqsofa"] > 0]

In [ ]:
#import pandas_profiling
#pandas_profiling.ProfileReport(d)

In [4]:
d_sep = pd.DataFrame(d_final)

In [ ]:
plt.scatter(x = d["alk_phos"], y = [0,0.5,1])
plt.show()

In [ ]:
pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
d_sep.describe()

In [5]:
pat_list = d_sep["patient_id"].unique()

In [6]:
d_pat = d[d["patient_id"].isin(pat_list)]

In [7]:
test = d_pat[d_pat['patient_id'] == 1437648]

In [8]:
test

,patient_id,encounter_id,time,loc_cat,unit1,unit2,IVF_meds,IVF_volume,IV_intake,avpu,...,gcs_score_sofa,creatinine_sofa,sofa_resp,sofa_coag,sofa_bili,sofa_card,sofa_gcs,sofa_cr,sofa_score,immuno_group
65,1437648,1867781,14mar2009 21:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
66,1437648,1867781,15mar2009 12:17:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
67,1437648,1867781,15mar2009 05:04:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
68,1437648,1867781,12mar2009 22:07:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
69,1437648,1867781,16mar2009 10:00:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
70,1437648,1867781,12mar2009 20:00:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,1.0,...,15,0.9,4,0,0,0,1,0,5,0
71,1437648,1867781,14mar2009 20:00:00,WARD,TS411 (room 181),NaN,100.0,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
72,1437648,1867781,16mar2009 00:25:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
73,1437648,1867781,15mar2009 20:00:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
74,1437648,1867781,14mar2009 05:12:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
75,1437648,1867781,16mar2009 09:29:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
76,1437648,1867781,15mar2009 13:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
77,1437648,1867781,12mar2009 22:00:00,WARD,TS417 (room 184),NaN,250.0,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
78,1437648,1867781,13mar2009 09:00:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,1.0,...,15,0.9,4,0,0,0,1,0,5,0
79,1437648,1867781,15mar2009 23:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
80,1437648,1867781,14mar2009 06:47:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
81,1437648,1867781,15mar2009 06:06:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
82,1437648,1867781,14mar2009 12:00:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
83,1437648,1867781,15mar2009 19:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
84,1437648,1867781,14mar2009 06:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
85,1437648,1867781,13mar2009 21:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
86,1437648,1867781,12mar2009 19:28:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
87,1437648,1867781,14mar2009 08:00:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
88,1437648,1867781,16mar2009 13:00:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
89,1437648,1867781,14mar2009 16:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
90,1437648,1867781,12mar2009 17:00:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,0.0,...,15,0.9,4,0,0,0,0,0,4,0
91,1437648,1867781,16mar2009 04:00:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
92,1437648,1867781,16mar2009 12:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
93,1437648,1867781,15mar2009 06:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
94,1437648,1867781,15mar2009 11:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,1437648,1867781,16mar2009 04:47:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
125,1437648,1867781,12mar2009 19:03:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
126,1437648,1867781,15mar2009 15:29:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
127,1437648,1867781,15mar2009 07:49:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
128,1437648,1867781,15mar2009 05:37:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
129,1437648,1867781,13mar2009 12:00:00,WARD,TS417 (room 184),NaN,50.0,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
130,1437648,1867781,13mar2009 00:36:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
131,1437648,1867781,13mar2009 11:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
132,1437648,1867781,16mar2009 11:00:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,1.0,...,15,0.9,4,0,0,0,1,0,5,0
133,1437648,1867781,12mar2009 18:46:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
134,1437648,1867781,13mar2009 00:25:00,WARD,TS417 (room 184),NaN,50.0,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
135,1437648,1867781,15mar2009 16:00:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,1.0,...,15,0.9,4,0,0,0,1,0,5,0
136,1437648,1867781,15mar2009 04:00:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
137,1437648,1867781,13mar2009 20:30:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,1.0,...,15,0.9,4,0,0,0,1,0,5,0
138,1437648,1867781,12mar2009 18:48:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
139,1437648,1867781,13mar2009 02:00:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,0.0,...,15,0.9,4,0,0,0,0,0,4,0
140,1437648,1867781,15mar2009 21:00:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
141,1437648,1867781,16mar2009 00:00:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
142,1437648,1867781,14mar2009 20:27:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
143,1437648,1867781,14mar2009 22:30:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
144,1437648,1867781,14mar2009 19:49:00,WARD,TS411 (room 181),NaN,NaN,NaN,NaN,NaN,...,15,1.0,4,0,0,0,1,0,5,0
145,1437648,1867781,13mar2009 19:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
146,1437648,1867781,16mar2009 13:23:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
147,1437648,1867781,12mar2009 19:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
148,1437648,1867781,14mar2009 00:00:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
149,1437648,1867781,12mar2009 18:45:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
150,1437648,1867781,12mar2009 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,0,0,4,0
151,1437648,1867781,13mar2009 19:51:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
152,1437648,1867781,13mar2009 00:00:00,WARD,TS417 (room 184),NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0
153,1437648,1867781,16mar2009 06:00:00,WARD,NaN,NaN,NaN,NaN,NaN,NaN,...,15,0.9,4,0,0,0,1,0,5,0

In [9]:
d_pat['encount_enum'] = d_pat.groupby(by = ['patient_id','encounter_id'])['encounter_id'].transform(pd.Series.value_counts)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [ ]:
d_pat.head(40)

In [10]:
d_pat.fillna(0)

,patient_id,encounter_id,time,loc_cat,unit1,unit2,IVF_meds,IVF_volume,IV_intake,avpu,...,creatinine_sofa,sofa_resp,sofa_coag,sofa_bili,sofa_card,sofa_gcs,sofa_cr,sofa_score,immuno_group,encount_enum
65,1437648,1867781,14mar2009 21:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.0,4,0,0,0,1,0,5,0,89
66,1437648,1867781,15mar2009 12:17:00,WARD,TS411 (room 181),0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,0,0,4,0,89
67,1437648,1867781,15mar2009 05:04:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.0,4,0,0,0,1,0,5,0,89
68,1437648,1867781,12mar2009 22:07:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
69,1437648,1867781,16mar2009 10:00:00,WARD,TS411 (room 181),0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
70,1437648,1867781,12mar2009 20:00:00,WARD,TS417 (room 184),0,0.0,0.0,0.0,1.0,...,0.9,4,0,0,0,1,0,5,0,89
71,1437648,1867781,14mar2009 20:00:00,WARD,TS411 (room 181),0,100.0,0.0,0.0,0.0,...,1.0,4,0,0,0,1,0,5,0,89
72,1437648,1867781,16mar2009 00:25:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
73,1437648,1867781,15mar2009 20:00:00,WARD,TS411 (room 181),0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
74,1437648,1867781,14mar2009 05:12:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
75,1437648,1867781,16mar2009 09:29:00,WARD,TS411 (room 181),0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
76,1437648,1867781,15mar2009 13:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,0,0,4,0,89
77,1437648,1867781,12mar2009 22:00:00,WARD,TS417 (room 184),0,250.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
78,1437648,1867781,13mar2009 09:00:00,WARD,TS417 (room 184),0,0.0,0.0,0.0,1.0,...,0.9,4,0,0,0,1,0,5,0,89
79,1437648,1867781,15mar2009 23:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
80,1437648,1867781,14mar2009 06:47:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.0,4,0,0,0,1,0,5,0,89
81,1437648,1867781,15mar2009 06:06:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
82,1437648,1867781,14mar2009 12:00:00,WARD,TS417 (room 184),0,0.0,0.0,0.0,0.0,...,1.0,4,0,0,0,1,0,5,0,89
83,1437648,1867781,15mar2009 19:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
84,1437648,1867781,14mar2009 06:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.0,4,0,0,0,1,0,5,0,89
85,1437648,1867781,13mar2009 21:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
86,1437648,1867781,12mar2009 19:28:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,0,0,4,0,89
87,1437648,1867781,14mar2009 08:00:00,WARD,TS417 (room 184),0,0.0,0.0,0.0,0.0,...,1.0,4,0,0,0,1,0,5,0,89
88,1437648,1867781,16mar2009 13:00:00,WARD,TS411 (room 181),0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
89,1437648,1867781,14mar2009 16:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.0,4,0,0,0,1,0,5,0,89
90,1437648,1867781,12mar2009 17:00:00,WARD,TS417 (room 184),0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,0,0,4,0,89
91,1437648,1867781,16mar2009 04:00:00,WARD,TS411 (room 181),0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
92,1437648,1867781,16mar2009 12:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
93,1437648,1867781,15mar2009 06:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,1,0,5,0,89
94,1437648,1867781,15mar2009 11:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,0,0,4,0,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169128,49177,2668016,15jan2009 01:00:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169129,49177,2668016,14jan2009 11:12:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.1,4,0,0,0,0,0,4,1,72
169130,49177,2668016,14jan2009 17:07:00,ER,S26 (room 739),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169131,49177,2668016,14jan2009 22:28:00,ER,S26 (room 739),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169132,49177,2668016,15jan2009 09:45:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169133,49177,2668016,15jan2009 01:21:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169134,49177,2668016,15jan2009 02:06:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169135,49177,2668016,14jan2009 19:27:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169136,49177,2668016,14jan2009 16:03:00,ER,S26 (room 739),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169137,49177,2668016,15jan2009 13:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169138,49177,2668016,15jan2009 05:45:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169139,49177,2668016,15jan2009 01:20:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169140,49177,2668016,15jan2009 12:34:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169141,49177,2668016,14jan2009 17:00:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169142,49177,2668016,14jan2009 12:47:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.1,4,0,0,0,0,0,4,1,72
169143,49177,2668016,14jan2009 10:27:00,0,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,0,0,4,1,72
169144,49177,2668016,16jan2009 09:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.7,4,0,0,0,0,1,5,1,72
169145,49177,2668016,15jan2009 09:00:00,WARD,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169146,49177,2668016,14jan2009 23:52:00,ER,S26 (room 739),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169147,49177,2668016,14jan2009 16:48:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169148,49177,2668016,14jan2009 00:00:00,0,0,0,0.0,0.0,0.0,0.0,...,0.9,4,0,0,0,0,0,4,1,72
169149,49177,2668016,14jan2009 19:00:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169150,49177,2668016,14jan2009 19:00:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169151,49177,2668016,14jan2009 20:23:00,ER,S26 (room 739),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169152,49177,2668016,16jan2009 00:00:00,WARD,TS563 (room 279),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169153,49177,2668016,14jan2009 20:24:00,ER,0,0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169154,49177,2668016,15jan2009 16:00:00,WARD,TS563 (room 279),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169155,49177,2668016,16jan2009 05:00:00,WARD,TS563 (room 279),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169156,49177,2668016,15jan2009 06:00:00,WARD,TS563 (room 279),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72
169157,49177,2668016,15jan2009 01:51:00,ER,S26 (room 739),0,0.0,0.0,0.0,0.0,...,1.5,4,0,0,0,0,1,5,1,72

In [ ]:
d_pat.head()

In [11]:
#combine antibiotic
abx_list = ["abx_iv", "abx_po", "antibiotic"]
d_pat['antibiotic_ad'] = d_pat[abx_list].sum(axis=1)
d_pat['antibiotic_ad'] = np.where(d_pat['antibiotic_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [12]:
d_pat.head(30)
del d_pat["abx_iv"], d_pat["abx_po"], d_pat["antibiotic"]

In [13]:
# combine antiarrhythmic meds
ant_arr = ["antiarrhythmic", "antiarrhythmic_iv", "antiarrhythmic_po"]
d_pat['antiarrhythmic_ad'] = d_pat[ant_arr].sum(axis=1)
d_pat['antiarrhythmic_ad'] = np.where(d_pat['antiarrhythmic_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [14]:
del d_pat["antiarrhythmic"], d_pat["antiarrhythmic_iv"], d_pat["antiarrhythmic_po"]

In [15]:
# combine anticoag meds
ant_coag = ["anticoag", "anticoag_iv", "anticoag_po"]
d_pat['anticoag_ad'] = d_pat[ant_coag].sum(axis=1)
d_pat['anticoag_ad'] = np.where(d_pat['anticoag_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [16]:
del d_pat["anticoag"], d_pat["anticoag_iv"], d_pat["anticoag_po"]

In [17]:
# combine antipsych meds
ant_coag = ["antipsych", "antipsych_iv", "antipsych_po"]
d_pat['antipsych_ad'] = d_pat[ant_coag].sum(axis=1)
d_pat['antipsych_ad'] = np.where(d_pat['antipsych_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [18]:
del d_pat["antipsych"], d_pat["antipsych_iv"], d_pat["antipsych_po"]

In [19]:
# combine avnodal meds
av_no = ["avnodal", "avnodal_iv", "avnodal_po"]
d_pat['avnodal_ad'] = d_pat[av_no].sum(axis=1)
d_pat['avnodal_ad'] = np.where(d_pat['avnodal_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [20]:
del d_pat["avnodal"], d_pat["avnodal_iv"], d_pat["avnodal_po"]

In [21]:
# combine diuretic meds
av_no = ["diuretic", "diuretic_iv", "diuretic_po"]
d_pat['diuretic_ad'] = d_pat[av_no].sum(axis=1)
d_pat['diuretic_ad'] = np.where(d_pat['diuretic_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [22]:
del d_pat["diuretic"], d_pat["diuretic_iv"], d_pat["diuretic_po"]

In [23]:
# combine antifungal meds
fung_no = ["fungal_iv", "fungal_po"]
d_pat['fungal_ad'] = d_pat[fung_no].sum(axis=1)
d_pat['fungal_ad'] = np.where(d_pat['fungal_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [24]:
del d_pat["fungal_iv"], d_pat["fungal_po"]

In [25]:
# combine hypoglycemic meds
#do not delete insulin
hypo_gly = ["hypoglycemic","hypoglycemic_iv", "hypoglycemic_po", "hypoglycemic_ins", "hypoglycemic_drip"]
d_pat['hypogly_ad'] = d_pat[hypo_gly].sum(axis=1)
d_pat['hpogly_ad'] = np.where(d_pat['hypogly_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [26]:
del d_pat["hypoglycemic"], d_pat["hypoglycemic_iv"], d_pat["hypoglycemic_po"], d_pat["hypoglycemic_drip"]

In [27]:
# combine immunosurp meds
immuno= ["immuno_group","immuno_iv", "immuno_po"]
d_pat['immuno_ad'] = d_pat[immuno].sum(axis=1)
d_pat['immuno_ad'] = np.where(d_pat['immuno_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [28]:
del d_pat["immuno_group"], d_pat["immuno_iv"], d_pat["immuno_po"]

In [29]:
# combine steroid meds
steroid= ["steroid_iv","steroid_po"]
d_pat['steroid_ad'] = d_pat[steroid].sum(axis=1)
d_pat['steroid_ad'] = np.where(d_pat['steroid_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [30]:
del d_pat["steroid_iv"], d_pat["steroid_po"]

In [31]:
# combine antiviral meds
antiviral= ["viral_iv","viral_po"]
d_pat['antiviral_ad'] = d_pat[antiviral].sum(axis=1)
d_pat['antiviral_ad'] = np.where(d_pat['antiviral_ad'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [32]:
del d_pat["viral_iv"], d_pat["viral_po"]

In [33]:
# count number of chest xrays
chest_xray= ["xr_abd","xr_abdwchest", "xr_initialportabd", "xr_initialportchest", "xr_lateralchest", "xr_portabd", "xr_portchest"]
d_pat['chest_xray'] = d_pat[chest_xray].sum(axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [34]:
del d_pat["xr_abd"],d_pat["xr_abdwchest"], d_pat["xr_initialportabd"], d_pat["xr_initialportchest"], d_pat["xr_lateralchest"], d_pat["xr_portabd"], d_pat["xr_portchest"]

In [35]:
# count number of CT CHEST/AB with contrast
chestab_ct= ["ct_abd_w", "ct_abdpelvis_w", "ct_chest_w", "ct_chestabd_w", "ct_chestabdpelvis_w", "ct_chestabdpelvisw", "ct_chestpe_w", "ct_chestw", "ct_pelvis_w"]
d_pat['chestab_w_ct'] = d_pat[chestab_ct].sum(axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [36]:
del d_pat["ct_abd_w"], d_pat["ct_abdpelvis_w"], d_pat["ct_chest_w"], d_pat["ct_chestabd_w"], d_pat["ct_chestabdpelvis_w"], d_pat["ct_chestabdpelvisw"], d_pat["ct_chestpe_w"], d_pat["ct_chestw"], d_pat["ct_pelvis_w"]

In [37]:
# count number of CT CHEST/AB without contrast
chestabwo_ct= ["ct_abd_wo", "ct_abdpelvis_wo", "ct_chest_wo", "ct_chestabd_wo", "ct_chestabdpelvis_wo", "ct_chestwo", "ct_pelvis_wo"]
d_pat['chestab_wo_ct'] = d_pat[chestabwo_ct].sum(axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [38]:
del d_pat["ct_abd_wo"], d_pat["ct_abdpelvis_wo"], d_pat["ct_chest_wo"], d_pat["ct_chestabd_wo"], d_pat["ct_chestabdpelvis_wo"], d_pat["ct_chestwo"], d_pat["ct_pelvis_wo"]

In [39]:
# count number of CT HEAD/NECK with contrast
headneckw_ct= ["ct_head_w", "ct_headneck_w", "ct_headw", "ct_neck_w"]
d_pat['headneck_w_ct'] = d_pat[headneckw_ct].sum(axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [40]:
del d_pat["ct_head_w"], d_pat["ct_headneck_w"], d_pat["ct_headw"], d_pat["ct_neck_w"]

In [41]:
# count number of CT HEAD/NECK without contrast
headneckw_ct= ["ct_head_wo", "ct_headneck_wo", "ct_headwo", "ct_neck_wo"]
d_pat['headneck_w_ct'] = d_pat[headneckw_ct].sum(axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [42]:
del d_pat["ct_head_wo"], d_pat["ct_headneck_wo"], d_pat["ct_headwo"], d_pat["ct_neck_wo"]

In [ ]:
d_pat.describe()

In [43]:
# Combine order for culture and culture of blood
cul_blood_ord= ["cul_blood", "culblood_order"]
d_pat['cul_blood_ord'] = d_pat[cul_blood_ord].sum(axis=1)
d_pat['cul_blood_ord'] = np.where(d_pat['cul_blood_ord'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [44]:
del d_pat["cul_blood"], d_pat["culblood_order"]

In [45]:
# Combine order for culture and culture of urine
cul_urine_ord= ["cul_urine", "culurine_order"]
d_pat['cul_urine_ord'] = d_pat[cul_urine_ord].sum(axis=1)
d_pat['cul_urine_ord'] = np.where(d_pat['cul_urine_ord'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [46]:
del d_pat["cul_urine"], d_pat["culurine_order"]

In [47]:
# Combine order for culture and culture of other
cul_other_ord= ["cul_other", "culother_order"]
d_pat['cul_other_ord'] = d_pat[cul_other_ord].sum(axis=1)
d_pat['cul_other_ord'] = np.where(d_pat['cul_other_ord'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [48]:
del d_pat["cul_other"], d_pat["culother_order"]

In [49]:
# Combine order for culture and culture of stool
cul_stool_ord= ["cul_stool", "culstool_order"]
d_pat['cul_stool_ord'] = d_pat[cul_stool_ord].sum(axis=1)
d_pat['cul_stool_ord'] = np.where(d_pat['cul_stool_ord'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [50]:
del d_pat["cul_stool"], d_pat["culstool_order"]

In [51]:
#Sum all comorbities (Elixhauser)
elix_comorb= ["elix_aids", "elix_alcohol","elix_bonemarrow","elix_chf","elix_coag","elix_cpd","elix_defanemia","elix_depression","elix_diabcomp","elix_diabuncomp","elix_drugs","elix_fluidelectro","elix_htncomp","elix_htnuncomp","elix_hypothyroid","elix_leukemia","elix_liverdis","elix_lossanemia","elix_lymphoma","elix_metacancer","elix_multmyeloma","elix_obesity","elix_otherneuro","elix_paralysis","elix_periphvasc","elix_psych","elix_pud","elix_pulmcirc","elix_renalfail","elix_rheumarth","elix_tumor","elix_valvdisease","elix_wtloss"]
d_pat['elix_comorb'] = d_pat[elix_comorb].sum(axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [52]:
del d_pat["elix_aids"], d_pat["elix_alcohol"], d_pat["elix_bonemarrow"], d_pat["elix_chf"], d_pat["elix_coag"], d_pat["elix_cpd"], d_pat["elix_defanemia"], d_pat["elix_depression"], d_pat["elix_diabcomp"], d_pat["elix_diabuncomp"], d_pat["elix_drugs"], d_pat["elix_fluidelectro"], d_pat["elix_htncomp"], d_pat["elix_htnuncomp"], d_pat["elix_hypothyroid"], d_pat["elix_leukemia"], d_pat["elix_liverdis"], d_pat["elix_lossanemia"], d_pat["elix_lymphoma"], d_pat["elix_metacancer"], d_pat["elix_multmyeloma"], d_pat["elix_obesity"], d_pat["elix_otherneuro"], d_pat["elix_paralysis"], d_pat["elix_periphvasc"], d_pat["elix_psych"], d_pat["elix_pud"], d_pat["elix_pulmcirc"], d_pat["elix_renalfail"], d_pat["elix_rheumarth"], d_pat["elix_tumor"], d_pat["elix_valvdisease"], d_pat["elix_wtloss"]

In [53]:
#Is there ever an instance where Nan means something --- or is it simply not there?
 # --assuming with following code that it means nothing

In [ ]:
d_pat.describe()

In [54]:
# Combine all urine cath
urin_cath= ["urinary_cath_care", "urinary_cath_device", "urinary_cath_indic", "urinary_cath_type", "urinary_bag_type"]
d_pat['urin_cath'] = d_pat[urin_cath].sum(axis=1)
d_pat['urin_cath'] = np.where(d_pat['urin_cath'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [55]:
del d_pat["urinary_cath_care"], d_pat["urinary_cath_device"], d_pat["urinary_cath_indic"], d_pat["urinary_cath_type"], d_pat["urinary_bag_type"]

In [56]:
# Sum all urine output -- assuming that if taken at same encounter peed multiple times and the more the are able to pee the better (in most cases)
urin_output= ["urinary_output", "urinary_output2", "urine_output"]
d_pat['urin_output'] = d_pat[urin_output].sum(axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [57]:
del d_pat["urinary_output"], d_pat["urinary_output2"], d_pat["urine_output"]

In [58]:
# Sum all mechanical ventilation
mech_ventil= ["vent", "vent01", "vent2"]
d_pat['mech_ventil'] = d_pat[mech_ventil].sum(axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [59]:
del d_pat["vent"], d_pat["vent01"], d_pat["vent2"]

In [60]:
# Combine all BENZODIAZEPINE
benzo_diaz= ["bzd_iv", "bzd_po"]
d_pat['benzo_diaz'] = d_pat[benzo_diaz].sum(axis=1)
d_pat['benzo_diaz'] = np.where(d_pat['benzo_diaz'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [61]:
del d_pat["bzd_iv"], d_pat["bzd_po"]

In [62]:
# Combine all DNR -- relabel to end_of_life
end_of_life= ["dncpr_dni", "dnr", "dnr_dni", "dnr_treatment_limit"]
d_pat['end_of_life'] = d_pat[end_of_life].sum(axis=1)
d_pat['end_of_life'] = np.where(d_pat['end_of_life'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [63]:
del d_pat["dncpr_dni"], d_pat["dnr"], d_pat["dnr_dni"], d_pat["dnr_treatment_limit"]

In [64]:
# Combine all ekg/ecg 
ekg_ecg= ["echo", "ekg_12leada", "ekg_12leadb"]
d_pat['ekg_ecg'] = d_pat[ekg_ecg].sum(axis=1)
d_pat['ekg_ecg'] = np.where(d_pat['ekg_ecg'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [65]:
del d_pat["echo"], d_pat["ekg_12leada"], d_pat["ekg_12leadb"]

In [66]:
#Combine all central line to show that central line was administered 
central_line= ["central_line_chest", "central_line_neck", "central_line_present"]
d_pat['central_line'] = d_pat[central_line].sum(axis=1)
d_pat['central_line'] = np.where(d_pat['central_line'] > 0, 1, 0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [67]:
del d_pat["central_line_present"], d_pat["central_line_neck"], d_pat["central_line_chest"]

In [68]:
#COMBINE UNITS or places the patient has been placed in the hospital
#change locations to dummy 
#aggregate
d_pat['mob_lo1'] = pd.get_dummies(d_pat['unit1']).sum(axis=1)
d_pat['mob_lo2'] = pd.get_dummies(d_pat['unit2']).sum(axis=1)
d_pat['mob_lo'] = d_pat['mob_lo1'] + d_pat['mob_lo2']
#for encounter groupby sum all

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [69]:
del d_pat["unit1"], d_pat["unit2"], d_pat["mob_lo1"], d_pat["mob_lo2"]

In [70]:
#AGE, we should just pick one -- 
d_pat['age_yr'] = d_pat['age']
#age
#age_ecart

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [71]:
del d_pat['age_ecart']

In [72]:
# ALBUMIN concat to one row and average if 2 vitals
d_pat.loc[d_pat['albumin'].isnull(),'albumin'] = d_pat['albumin_ecart']
d_pat.loc[d_pat['albumin_ecart'].isnull(),'albumin_ecart'] = d_pat['albumin']
d_pat['albumin_c'] = (d_pat['albumin'] + d_pat['albumin_ecart'])/2
#albumin
#albumin_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [73]:
del d_pat['albumin'], d_pat['albumin_ecart']

In [74]:
# ALKALINE PHOSPHATE concat to one row and average if 2 vitals
d_pat.loc[d_pat['alk_phos'].isnull(),'alk_phos'] = d_pat['alk_phos_ecart']
d_pat.loc[d_pat['alk_phos_ecart'].isnull(),'alk_phos_ecart'] = d_pat['alk_phos']
d_pat['allphos_c'] = (d_pat['alk_phos'] + d_pat['alk_phos_ecart'])/2
#alk_phos
#alk_phos_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [75]:
del d_pat['alk_phos'], d_pat['alk_phos_ecart']

In [76]:
# ANION GAP concat to one row and average if 2 vitals
d_pat.loc[d_pat['anion_gap'].isnull(),'anion_gap'] = d_pat['anion_gap_ecart']
d_pat.loc[d_pat['anion_gap_ecart'].isnull(),'anion_gap_ecart'] = d_pat['anion_gap']
d_pat['albumin_c'] = (d_pat['anion_gap'] + d_pat['anion_gap_ecart'])/2
#anion_gap
#anion_gap_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [77]:
del d_pat['anion_gap'], d_pat['anion_gap_ecart']

In [78]:
# AVPU concat to one row and average if 2 vitals
d_pat.loc[d_pat['avpu'].isnull(),'avpu'] = d_pat['avpu_ecart']
d_pat.loc[d_pat['avpu_ecart'].isnull(),'avpu_ecart'] = d_pat['avpu']
d_pat.loc[d_pat['avpu_old'].isnull(),'avpu_old'] = d_pat['avpu_sofa']
d_pat.loc[d_pat['avpu_sofa'].isnull(),'avpu_sofa'] = d_pat['avpu_old']
d_pat.loc[d_pat['avpu'].isnull(),'avpu'] = d_pat['avpu_old']
d_pat.loc[d_pat['avpu_old'].isnull(),'avpu_old'] = d_pat['avpu']
d_pat.loc[d_pat['avpu'].isnull(),'avpu'] = d_pat['avpu_sofa']
d_pat.loc[d_pat['avpu_sofa'].isnull(),'avpu_sofa'] = d_pat['avpu']
d_pat.loc[d_pat['avpu_old'].isnull(),'avpu_old'] = d_pat['avpu_ecart']
d_pat.loc[d_pat['avpu_ecart'].isnull(),'avpu_ecart'] = d_pat['avpu_old']
d_pat.loc[d_pat['avpu_sofa'].isnull(),'avpu_sofa'] = d_pat['avpu_ecart']
d_pat.loc[d_pat['avpu_ecart'].isnull(),'avpu_ecart'] = d_pat['avpu_sofa']
d_pat['avpu_c'] = (d_pat['avpu'] + d_pat['avpu_ecart'] + d_pat['avpu_sofa'] + d_pat['avpu_old'])/4
#avpu
#avpu_ecart
#avpu_old
#avpu_sofa
#NEED TO CORRECT TO CHOOSE ALL --- SEE IF REALLY NEED TO REPLACE?
#AVPU SOFA AND ECART SEEM TO BE THE SAME

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [79]:
del d_pat['avpu'], d_pat['avpu_ecart'], d_pat['avpu_old'], d_pat['avpu_sofa']

In [80]:
# TOTAL BILIRUBIN concat to one row and average if 2 vitals
d_pat.loc[d_pat['bili_total'].isnull(),'bili_total'] = d_pat['bili_total_ecart']
d_pat.loc[d_pat['bili_total_ecart'].isnull(),'bili_total_ecart'] = d_pat['bili_total']
d_pat.loc[d_pat['bili_total_sofa'].isnull(),'bili_total_sofa'] = d_pat['bili_total']
d_pat.loc[d_pat['bili_total'].isnull(),'bili_total'] = d_pat['bili_total_sofa']
d_pat.loc[d_pat['bili_total_sofa'].isnull(),'bili_total_sofa'] = d_pat['bili_total_ecart']
d_pat.loc[d_pat['bili_total_ecart'].isnull(),'bili_total_ecart'] = d_pat['bili_total_sofa']
d_pat['albumin_c'] = (d_pat['bili_total'] + d_pat['bili_total_ecart'] + d_pat['bili_total_sofa'])/3
#bili_total
#bili_total_ecart
#bili_total_sofa
#NEED TO WRITE A FUNCTION FOR THIS ^

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [81]:
del d_pat['bili_total'], d_pat['bili_total_ecart'], d_pat['bili_total_sofa']

In [82]:
# BLOOD UREA NITROGEN TEST
d_pat.loc[d_pat['bun'].isnull(),'bun'] = d_pat['bun_ecart']
d_pat.loc[d_pat['bun_ecart'].isnull(),'bun_ecart'] = d_pat['bun']
d_pat['bun_c'] = (d_pat['bun'] + d_pat['bun_ecart'])/2
#bun
#bun_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [83]:
del d_pat['bun'], d_pat['bun_ecart']

In [84]:
# BLOOD UREA NITROGEN TO CREATININE RATIO
d_pat.loc[d_pat['bun_cr_ratio'].isnull(),'bun_cr_ratio'] = d_pat['bun_cr_ratio_ecart']
d_pat.loc[d_pat['bun_cr_ratio_ecart'].isnull(),'bun_cr_ratio_ecart'] = d_pat['bun_cr_ratio']
d_pat['bun_cr_c'] = (d_pat['bun_cr_ratio'] + d_pat['bun_cr_ratio_ecart'])/2
#bun_cr_ratio
#bun_cr_ratio_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [85]:
del d_pat['bun_cr_ratio'], d_pat['bun_cr_ratio_ecart']

In [86]:
# CALCIUM
d_pat.loc[d_pat['calcium'].isnull(),'calcium'] = d_pat['calcium_ecart']
d_pat.loc[d_pat['calcium_ecart'].isnull(),'calcium_ecart'] = d_pat['calcium']
d_pat['calcium_c'] = (d_pat['calcium'] + d_pat['calcium_ecart'])/2
#calcium
#calcium_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [87]:
del d_pat['calcium'], d_pat['calcium_ecart']

In [88]:
# CO2
d_pat.loc[d_pat['co2'].isnull(),'co2'] = d_pat['co2_ecart']
d_pat.loc[d_pat['co2_ecart'].isnull(),'co2_ecart'] = d_pat['co2']
d_pat['co2_c'] = (d_pat['co2'] + d_pat['co2_ecart'])/2

#co2
#co2_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [89]:
del d_pat['co2'], d_pat['co2_ecart']

In [90]:
#creatinine
d_pat.loc[d_pat['creatinine'].isnull(),'creatinine'] = d_pat['creatinine_ecart']
d_pat.loc[d_pat['creatinine_ecart'].isnull(),'creatinine_ecart'] = d_pat['creatinine']
d_pat.loc[d_pat['creatinine_ecart'].isnull(),'creatinine_ecart'] = d_pat['creatinine_sofa']
d_pat.loc[d_pat['creatinine_sofa'].isnull(),'creatinine_sofa'] = d_pat['creatinine_ecart']
d_pat.loc[d_pat['creatinine_sofa'].isnull(),'creatinine_sofa'] = d_pat['creatinine']
d_pat.loc[d_pat['creatinine'].isnull(),'creatinine'] = d_pat['creatinine_sofa']
d_pat['creatinine_c'] = (d_pat['creatinine'] + d_pat['creatinine_ecart'] + d_pat['creatinine_sofa'])/3
#creatinine
#creatinine_ecart
#creatinine_sofa

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [91]:
del d_pat['creatinine'], d_pat['creatinine_ecart'], d_pat['creatinine_sofa']

In [92]:
# DBP
d_pat.loc[d_pat['dbp'].isnull(),'dbp'] = d_pat['dbp_ecart']
d_pat.loc[d_pat['dbp_ecart'].isnull(),'dbp_ecart'] = d_pat['dbp']
d_pat.loc[d_pat['dbp_ecart'].isnull(),'dbp_ecart'] = d_pat['dbp_sofa']
d_pat.loc[d_pat['dbp_sofa'].isnull(),'dbp_sofa'] = d_pat['dbp_ecart']
d_pat.loc[d_pat['dbp'].isnull(),'dbp'] = d_pat['dbp_sofa']
d_pat.loc[d_pat['dbp_sofa'].isnull(),'dbp_sofa'] = d_pat['dbp']
d_pat['dbp_c'] = (d_pat['dbp'] + d_pat['dbp_ecart'] + d_pat['dbp_sofa'])/3
#dbp
#dbp_ecart
#dbp_sofa

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [93]:
del d_pat['dbp'], d_pat['dbp_ecart'], d_pat['dbp_sofa']

In [94]:
# GLUCOSE SERUM
d_pat.loc[d_pat['gluc_ser'].isnull(),'gluc_ser'] = d_pat['gluc_ser_ecart']
d_pat.loc[d_pat['gluc_ser_ecart'].isnull(),'gluc_ser_ecart'] = d_pat['gluc_ser']
d_pat['gluc_ser_c'] = (d_pat['gluc_ser'] + d_pat['gluc_ser_ecart'])/2
#gluc_ser
#gluc_ser_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [95]:
del d_pat['gluc_ser'], d_pat['gluc_ser_ecart']

In [96]:
#HEMAGLOBIN
d_pat.loc[d_pat['hb'].isnull(),'hb'] = d_pat['hb_ecart']
d_pat.loc[d_pat['hb_ecart'].isnull(),'hb_ecart'] = d_pat['hb']
d_pat['hb_c'] = (d_pat['hb'] + d_pat['hb_ecart'])/2
#hb
#hb_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [97]:
del d_pat['hb'], d_pat['hb_ecart']

In [ ]:
# HEART RATE
d_pat.loc[d_pat['hr'].isnull(),'hr'] = d_pat['hr_ecart']
d_pat.loc[d_pat['hr_ecart'].isnull(),'hr_ecart'] = d_pat['hr']
d_pat['hr_c'] = (d_pat['hr'] + d_pat['hr_ecart'])/2
#hr
#hr_ecart

In [98]:
del d_pat['hr'], d_pat['hr_ecart']

In [99]:
# OXYGEN SATURATION
d_pat.loc[d_pat['o2sat'].isnull(),'o2sat'] = d_pat['o2sat_ecart']
d_pat.loc[d_pat['o2sat_ecart'].isnull(),'o2sat_ecart'] = d_pat['o2sat']
d_pat['o2sat_c'] = (d_pat['o2sat'] + d_pat['o2sat_ecart'])/2
#o2sat
#o2sat_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [102]:
del d_pat['o2sat'], d_pat['o2sat_ecart']

In [103]:
#PLATELET COUNT
d_pat.loc[d_pat['platelet_count'].isnull(),'platelet_count'] = d_pat['platelet_count_ecart']
d_pat.loc[d_pat['platelet_count_ecart'].isnull(),'platelet_count_ecart'] = d_pat['platelet_count']
d_pat.loc[d_pat['platelet_count_ecart'].isnull(),'platelet_count_ecart'] = d_pat['platelet_count_sofa']
d_pat.loc[d_pat['platelet_count_sofa'].isnull(),'platelet_count_sofa'] = d_pat['platelet_count_ecart']
d_pat.loc[d_pat['platelet_count_sofa'].isnull(),'platelet_count_sofa'] = d_pat['platelet_count']
d_pat.loc[d_pat['platelet_count'].isnull(),'platelet_count'] = d_pat['platelet_count_sofa']
d_pat['platelet_count_c'] = (d_pat['platelet_count_sofa'] + d_pat['platelet_count_ecart'] + d_pat['platelet_count'])/3
#platelet_count
#platelet_count_ecart
#platelet_count_sofa

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [104]:
del d_pat['platelet_count'], d_pat['platelet_count_ecart'], d_pat['platelet_count_sofa']

In [105]:
# POTASSIUM
d_pat.loc[d_pat['potassium'].isnull(),d_pat['potassium']] = d_pat['potassium_ecart']
d_pat.loc[d_pat['potassium_ecart'].isnull(),'potassium_ecart'] = d_pat['potassium']
d_pat['potassium_c'] = (d_pat['potassium_ecart'] + d_pat['potassium'])/2
#potassium
#potassium_ecart

KeyError: '[nan nan nan ... nan nan nan] not in index'

In [ ]:
del d_pat['potassium'], d_pat['potassium_ecart']

In [106]:
# PROTON INHIB
d_pat.loc[d_pat['ppi'].isnull(),'ppi'] = d_pat['ppi_ecart']
d_pat.loc[d_pat['ppi_ecart'].isnull(),'ppi_ecart'] = d_pat['ppi']
d_pat['ppi_c'] = (d_pat['ppi'] + d_pat['ppi_ecart'])/2
#ppi
#ppi_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [107]:
del d_pat['ppi'], d_pat['ppi_ecart']

In [108]:
# RESPIRATORY RATE
d_pat.loc[d_pat['rr'].isnull(),'rr'] = d_pat['rr_ecart']
d_pat.loc[d_pat['rr_ecart'].isnull(),'rr_ecart'] = d_pat['rr']
d_pat['rr_c'] = (d_pat['rr'] + d_pat['rr_ecart'])/2
#rr
#rr_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [109]:
del d_pat['rr'], d_pat['rr_ecart']

In [110]:
# SPONTANEOUS BACTERIAL PERITONITIS
d_pat.loc[d_pat['sbp'].isnull(),'sbp'] = d_pat['sbp_ecart']
d_pat.loc[d_pat['sbp_ecart'].isnull(),'sbp_ecart'] = d_pat['sbp']
d_pat.loc[d_pat['sbp_ecart'].isnull(),'sbp_ecart'] = d_pat['sbp_sofa']
d_pat.loc[d_pat['sbp_sofa'].isnull(),'sbp_sofa'] = d_pat['sbp_ecart']
d_pat.loc[d_pat['sbp'].isnull(),'sbp'] = d_pat['sbp_sofa']
d_pat.loc[d_pat['sbp_sofa'].isnull(),'sbp_sofa'] = d_pat['sbp']
d_pat['sbp_c'] = (d_pat['sbp'] + d_pat['sbp_ecart'] + d_pat['sbp_sofa'])/3
#sbp
#sbp_ecart
#sbp_sofa

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [111]:
del d_pat['sbp'], d_pat['sbp_ecart'], d_pat['sbp_sofa']

In [112]:
#AST (SGOT)
d_pat.loc[d_pat['sgot'].isnull(),'sgot'] = d_pat['sgot_ecart']
d_pat.loc[d_pat['sgot_ecart'].isnull(),'sgot_ecart'] = d_pat['sgot']
d_pat['sgot_c'] = (d_pat['sgot'] + d_pat['sgot_ecart'])/2
#sgot
#sgot_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [113]:
del d_pat['sgot'], d_pat['sgot_ecart']

In [114]:
# SODIUM
d_pat.loc[d_pat['sodium'].isnull(),'sodium'] = d_pat['sodium_ecart']
d_pat.loc[d_pat['sodium_ecart'].isnull(),'sodium_ecart'] = d_pat['sodium']
d_pat['sodium_c'] = (d_pat['sodium'] + d_pat['sodium_ecart'])/2
#sodium
#sodium_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [115]:
del d_pat['sodium'], d_pat['sodium_ecart']

In [116]:
#WHITE BLOODCELL COUNT
d_pat.loc[d_pat['wbc'].isnull(),'wbc'] = d_pat['wbc_ecart']
d_pat.loc[d_pat['wbc_ecart'].isnull(),'wbcecart'] = d_pat['wbc']
d_pat['wbc_c'] = (d_pat['wbc'] + d_pat['wbc_ecart'])/2
#wbc
#wbc_ecart

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:357: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [117]:
del d_pat['wbc'], d_pat['wbc_ecart']

In [ ]:
# List of units sent to, think of it as mobility throughout the hospital
d_pat['mod_hosp'] = d_pat.groupby('encounter_id')['mob_lo1'].apply(list)
d_pat['mod_hosp2'] = d_pat.groupby('encounter_id')['unit2'].sum()
#Combine all central line to show that central line was administered 
central_line= ["central_line_chest", "central_line_neck", "central_line_present"]
d_pat['central_line'] = d_pat[central_line].sum(axis=1)
d_pat['central_line'] = np.where(d_pat['central_line'] > 0, 1, 0)

In [ ]:
d_septic = d_pat[d_pat['infxnqsofa'] == 1]

In [ ]:
d_septic.describe()

In [ ]:
from numpy import *
from collections import Counter
septic = d_septic["patient_id"].unique()
Counter(d_septic["patient_id"])
#will need to append all instances by occurance? Or do we want to leave seperate because we're looking at readmission after sepsis
#leave format for now

In [ ]:
#merge 2 datasets by patient_id
sep_encs = pd.merge(d_septic, d_pat, how='left', on=['patient_id'])
sep_encs.to_csv('sep_en_1.csv')

In [ ]:
sep_encs.describe()
sep_encs.head(40)

In [ ]:
from pandasql import *
#sqllite3 commands accepted

In [ ]:
pysqldf = lambda q: sqldf(q, globals())
q  = """
SELECT a.Name               AS ArticleName
     , GROUP_CONCAT(t.Name) AS TagList
FROM Articles AS a
  LEFT JOIN ArticlesTags AS at
    ON at.ArticleId = a.Id
  LEFT JOIN Tags AS t
    ON t.Id = at.TagId
GROUP BY a.Id, a.Name ;
"""

In [ ]:
#df = pysqldf(q)

In [ ]:
import csv

d_pat.to_csv('df.csv')

In [ ]:
#df_col = list(d.columns)
#dd = {}
#for i in df_col:
#    dd.update({i:d[i].unique()})
#    += dd[i].append(d[i].unique())
#for col in d.columns:
#df_col['avpu_ecart'].append(d['avpu_ecart'].unique())
#print(col)