In [1]:
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

In [2]:
import pandas as pd
import pandasql

#filename = 'condensed_sepsis.csv'
s_data = pd.DataFrame.from_csv('encounter_level_comp.csv', index_col=None)
s_data = s_data.drop(s_data.columns[0], axis=1)
s_data.describe()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """

,patient_id,encounter_id,loc_cat,maxIVF_meds,countIVF_meds,maxIVF_volume,avgIVF_volume,maxIV_intake,maxfio2,avgfio2,...,avgo2sat_c,avgplatelet_count_c,minplatelet_count_c,avgppi_c,avgrr_c,avgsbp_c,avgsgot_c,avgsodium_c,avgwbc_c,minwbc_c
count,4.050000e+02,4.050000e+02,405.000000,288.000000,405.000000,0.0,0.0,0.0,70.000000,70.000000,...,405.000000,405.000000,405.000000,405.000000,405.000000,405.000000,405.000000,405.000000,405.000000,405.000000
mean,9.582374e+05,2.405041e+06,261.797531,0.553060,22.619753,NaN,NaN,NaN,0.906917,-0.086816,...,0.021773,0.080394,-0.462634,-0.024932,-0.072018,0.117463,-0.047251,0.013036,-0.076168,-0.456277
std,6.394073e+05,1.327188e+05,406.431590,5.540364,53.033696,NaN,NaN,NaN,1.500591,1.143622,...,0.454163,0.796662,0.416447,0.619669,0.396491,0.697960,0.619481,0.665244,1.039251,0.273638
min,4.158000e+03,1.867781e+06,20.000000,-0.179130,0.000000,NaN,NaN,NaN,-2.542111,-2.542111,...,-2.385630,-1.454742,-1.522313,-2.117551,-1.002768,-1.819160,-0.125251,-2.116247,-0.843145,-0.928669
25%,2.901360e+05,2.304921e+06,80.000000,-0.040503,0.000000,NaN,NaN,NaN,-0.685318,-0.705430,...,-0.193515,-0.411567,-0.684274,-0.428927,-0.297469,-0.378289,-0.105550,-0.351933,-0.397041,-0.591444
50%,1.016483e+06,2.354733e+06,145.000000,0.236750,7.000000,NaN,NaN,NaN,2.197597,-0.388192,...,0.092959,-0.007550,-0.247795,-0.064989,-0.141136,0.068481,-0.096931,0.059850,-0.221284,-0.430861
75%,1.463725e+06,2.525686e+06,258.000000,0.236750,22.000000,NaN,NaN,NaN,2.246460,0.555392,...,0.330571,0.467500,-0.160499,0.383727,0.057011,0.577441,-0.083854,0.405333,0.002554,-0.294366
max,1.929412e+06,2.668016e+06,3429.000000,94.040862,434.000000,NaN,NaN,NaN,2.246460,2.246460,...,0.826274,4.869790,1.856032,2.263265,2.152994,2.449994,12.231616,3.415396,15.281930,3.712180

In [3]:
q  = """
SELECT *
FROM s_data
WHERE maxinfxnqsofa = 1;
"""

sep = pysqldf(q)

In [4]:

sep.describe()

,patient_id,encounter_id,loc_cat,maxIVF_meds,countIVF_meds,maxfio2,avgfio2,maxfio2_vent,avgfio2_vent,maxgastric_output,...,avgo2sat_c,avgplatelet_count_c,minplatelet_count_c,avgppi_c,avgrr_c,avgsbp_c,avgsgot_c,avgsodium_c,avgwbc_c,minwbc_c
count,3.730000e+02,3.730000e+02,373.000000,279.000000,373.000000,67.000000,67.000000,42.000000,42.000000,53.000000,...,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000
mean,9.642788e+05,2.400243e+06,275.879357,0.569337,24.410188,0.970918,-0.067037,2.348682,0.028897,0.695082,...,0.015324,0.063110,-0.468895,-0.016762,-0.064164,0.115260,-0.045114,0.015658,-0.085488,-0.456176
std,6.383691e+05,1.319164e+05,419.887170,5.628492,54.865923,1.438968,1.083104,4.650366,0.530095,1.960963,...,0.449363,0.769652,0.418880,0.628562,0.407163,0.699198,0.644757,0.673766,0.968300,0.280488
min,4.158000e+03,1.867781e+06,21.000000,-0.179130,0.000000,-2.542111,-2.542111,-0.529265,-0.529265,-0.558878,...,-2.385630,-1.454742,-1.522313,-2.117551,-1.002768,-1.819160,-0.125251,-2.116247,-0.843145,-0.928669
25%,3.136920e+05,2.304041e+06,85.000000,-0.040503,0.000000,-0.685318,-0.696900,1.011619,-0.346792,-0.546313,...,-0.193515,-0.427700,-0.697368,-0.428927,-0.297469,-0.380346,-0.105550,-0.351933,-0.387141,-0.591444
50%,1.025117e+06,2.353769e+06,158.000000,0.236750,8.000000,2.246460,-0.384863,1.525247,-0.109802,-0.181931,...,0.088389,-0.031668,-0.258707,-0.036693,-0.123428,0.070735,-0.096931,0.049229,-0.217663,-0.430861
75%,1.466868e+06,2.520285e+06,275.000000,0.236750,24.000000,2.246460,0.554167,1.525247,0.243239,0.802319,...,0.322678,0.461331,-0.160499,0.386942,0.069239,0.577441,-0.083845,0.408778,0.004591,-0.294366
max,1.929412e+06,2.668016e+06,3429.000000,94.040862,434.000000,2.246460,2.246460,21.727942,1.525247,6.980056,...,0.826274,3.596990,1.856032,2.263265,2.152994,2.449994,12.231616,3.415396,15.281930,3.712180

In [5]:
f  = """
SELECT sep.*, 
s_data.encounter_id as encounter_id_p1, 
s_data.mintime as mintime_p1, s_data.maxtime as maxtime_p1, 
s_data.loc_cat as loc_cat_p1, 
s_data.maxIVF_meds as maxIVF_meds_p1, s_data.countIVF_meds as countIVF_meds_p1, 
s_data.maxIVF_volume as maxIVF_volume_p1, s_data.avgIVF_volume as avgIVF_volume_p1, 
s_data.maxIV_intake as maxIV_intake_p1,
s_data.maxfio2 as maxfio2_p1, s_data.avgfio2 as avgfio2_p1, 
s_data.maxfio2_vent as maxfio2_vent1, s_data.avgfio2_vent as avgfio2_vent_p1, 
s_data.maxgastric_output as maxgastric_output_p1, s_data.mingastric_output as mingastric_output_p1, s_data.avggastric_output as avggastric_output_p1, 
s_data.maxgcs_eye as maxgcs_eye_p1, s_data.mingcs_eye as mingcs_eye_p1, 
s_data.maxgcs_motor as maxgcs_motor_p1, s_data.mingcs_motor as mingcs_motor_p1, 
s_data.maxgcs_score as maxgcs_score_p1, s_data.avggcs_score as avggcs_score_p1, 
s_data.maxgcs_verbal as maxgcs_verbal_p1, s_data.mingcs_verbal as mingcs_verbal_p1, 
s_data.maxhfo_fio2 as maxhfo_fio2_p1, s_data.avghfo_fio2 as avghfo_fio2_p1, 
s_data.maxmap_notcalc as maxmap_notcalc_p1, s_data.minmap_notcalc as minmap_notcalc_p1, s_data.avgmap_notcalc as avgmap_notcalc_p1, 
s_data.maxmap_zzz as maxmap_zzz_p1, s_data.minmap_zzz as minmap_zzz_p1, s_data.avgmap_zzz as avgmap_zzz_p1, 
s_data.maxnasal_cannula as maxnasal_cannula_p1, 
s_data.maxni_fio2 as maxni_fio2_p1, s_data.avgni_fio2 as avgni_fio2_p1, 
s_data.maxni_vent as maxni_vent_p1, 
s_data.maxo2_device as maxo2_device_p1, 
s_data.maxo2_flow as maxo2_flow_p1, s_data.mino2_flow as mino2_flow_p1, s_data.avgo2_flow as avgo2_flow_p1, 
s_data.maxrass as maxrass_p1, s_data.minrass as minrass1, s_data.avgrass as avgrass_p1, 
s_data.maxroomair as maxroomair_p1, 
s_data.mintemp as mintemp_p1, s_data.maxtemp as maxtemp_p1, 
s_data.maxtube_output as maxtube_output_p1, s_data.avgtube_output as avgtube_output_p1, 
s_data.maxwound_output as maxwound_output_p1, s_data.avgwound_output as avgwound_output_p1, 
s_data.maxfio2_final as maxfio2_final_p1, 
s_data.maxfio2_final2 as maxfio2_final2_p1, 
s_data.maxsf_ratio_old as maxsf_ratio_old_p1, s_data.avgsf_ratio_old as avgsf_ratio_old_p1, 
s_data.maxcontam_true as maxcontam_true_p1, 
s_data.maxstaph as maxstaph_p1, 
s_data.maxabs_bands as maxabs_bands_p1, s_data.minabs_bands as minabs_bands_p1, s_data.avgabs_bands as avgabs_bands_p1, 
s_data.maxabs_neutrophils as maxabs_neutrophils_p1, s_data.maxabs_neutrophils as maxabs_neutrophil_p1, s_data.avgabs_neutrophils as avgabs_neutrophils_p1, 
s_data.maxalt as maxalt_p1, s_data.minalt as minalt1, s_data.avgalt as avgalt_p1, 
s_data.maxantitrypsin as maxantitrypsin_p1, s_data.avgantitrypsin as avgantitrypsin_p1, 
s_data.maxauto_abs_neutrophils as maxauto_abs_neutrophils_p1, s_data.minauto_abs_neutrophils as minauto_abs_neutrophils_p1, 
s_data.maxbands as maxbands_p1, s_data.minbands as minbands_p1, s_data.avgbands as avgbands_p1, 
s_data.maxbasophils as maxbasophils_p1, s_data.minbasophils as minbasophils_p1, s_data.avgbasophils as avgbasophils_p1, 
s_data.maxblasts as maxblasts_p1, s_data.minblasts as minblasts_p1, s_data.avgblasts as avgblasts_p1, 
s_data.mincdiff as mincdiff_p1, s_data.maxcdiff as maxcdiff_p1, s_data.sumcdiff as sumcdiff_p1, 
s_data.maxchloride as maxchloride_p1, s_data.minchloride as minchloride_p1, s_data.avgchloride as avgchloride_p1, 
s_data.maxcortisol as maxcortisol_p1, s_data.mincortisol as mincortisol_p1, s_data.avgcortisol as avgcortisol_p1, 
s_data.maxcrp as maxcrp_p1, s_data.mincrp as mincrp_p1, s_data.avgcrp as avgcrp_p1, 
s_data.maxcul_cathtip as maxcul_cathtip_p1, 
s_data.maxcul_csf as maxcul_csf_p1, 
s_data.maxcul_influenza as maxcul_influenza_p1, 
s_data.maxcul_mrsa as maxcul_mrsa_p1, 
s_data.maxcul_parainfluenza as maxcul_parainfluenza_p1, 
s_data.maxcul_resp as maxcul_resp_p1, 
s_data.maxeosinophils as maxeosinophils_p1, s_data.avgeosinophils as avgeosinophils_p1, 
s_data.maxesr as maxesr_p1, s_data.avgesr as avgesr_p1, 
s_data.maxhb1198 as maxhb1198_p1, s_data.avghb1198 as avghb1198_p1, 
s_data.maxhb1200 as maxhb1200_p1, s_data.avghb1200 as avghb1200_p1, 
s_data.maxhc03 as maxhc03_p1, 
s_data.maxhc03_ven as maxhc03_ven_p1, s_data.avghc03_ven as avghc03_ven_p1, 
s_data.maxhco3_art as maxhco3_art_p1, 
s_data.maxhematocrit as maxhematocrit_p1, s_data.minhematocrit as minhematocrit_p1, s_data.avghematocrit as avghematocrit_p1, 
s_data.maxinr as maxinr_p1, s_data.avginr as avginr_p1, 
s_data.maxketones as maxketones_p1, s_data.minketones as minketones_p1, s_data.avgketones as avgketones_p1, 
s_data.maxlactate1 as maxlactate1_p1, s_data.avglactate1 as avglactate1_p1, 
s_data.maxlactate_wholebld1434 as maxlactate_wholebld1434_p1, s_data.avglactate_wholebld1434 as avglactate_wholebld1434_p1, 
s_data.maxlactate_wholebld4303 as maxlactate_wholebld4303_p1, s_data.avglactate_wholebld4303 as avglactate_wholebld4303_p1, 
s_data.maxlactic_acid as maxlactic_acid_p1, s_data.minlactic_acid as minlactic_acid_p1, s_data.avglactic_acid as avglactic_acid_p1, 
s_data.maxlipase as maxlipase_p1, s_data.minlipase as minlipase_p1, s_data.lipase as avglipase_p1, 
s_data.maxlymphocytes as maxlymphocytes_p1, s_data.minlymphocytes as minlymphocytes_p1, s_data.avglymphocytes as avglymphocytes_p1, 
s_data.maxmagnesium as maxmagnesium_p1, s_data.minmagnesium as minmagnesium_p1, s_data.avgmagnesium as avgmagnesium_p1, 
s_data.maxmcv as maxmcv_p1, s_data.avgmcv as avgmcv_p1, 
s_data.maxmetamyelocytes as maxmetamyelocytes_p1, s_data.minmetamyelocytes as minmetamyelocytes_p1, s_data.avgmetamyelocytes as avgmetamyelocytes_p1, 
s_data.maxmonocytes as maxmonocytes_p1, s_data.minmonocytes as minmonocytes_p1, s_data.avgmonocytes as avgmonocytes_p1, 
s_data.maxneutrophils as maxneutrophils_p1, s_data.minneutrophils as minneutrophils_p1, s_data.avgneutrophils as avgneutrophils_p1, 
s_data.maxnrbc as maxnrbc_p1, s_data.avgnrbc as avgnrbc_p1, 
s_data.maxosmolality as maxosmolality_p1, s_data.minosmolality as minosmolality_p1, s_data.avgosmolality as avgosmolality_p1, 
s_data.maxpaco2 as maxpaco2_p1, s_data.avgpaco2 as avgpaco2_p1, 
s_data.maxpao2 as maxpao2_p1, s_data.avgpao2 as avgpao2_p1, 
s_data.maxpco2_1097 as maxpco2_1097_p1, 
s_data.maxpco2_4098 as maxpco2_4098_p1, 
s_data.maxph1250 as maxph1250_p1, s_data.avgph1250 as avgph1250_p1, 
s_data.maxph1819 as maxph1819_p1, s_data.avgph1819 as avgph1819_p1, 
s_data.maxph272 as maxph272_p1, s_data.avgph272 as avgph272_p1, 
s_data.maxph4315 as maxph4315_p1, s_data.avgph4315 as avgph4315_p1, 
s_data.maxph690 as maxph690_p1, s_data.avgph690 as avgph690_p1, 
s_data.maxphosphate as maxphosphate_p1, s_data.minphosphate as minphosphate_p1, s_data.avgphosphate as avgphosphate_p1,
s_data.maxpotassium as maxpotassium_p1, s_data.minpotassium as minpotassium_p1, s_data.avgpotassium as avgpotassium_p1, 
s_data.maxpromyelocytes as maxpromyelocytes_p1, s_data.avgpromyelocytes as avgpromyelocytes_p1, 
s_data.maxtotal_protein as maxtotal_protein_p1, s_data.avgtotal_protein as avgtotal_protein_p1, 
s_data.maxptt as maxptt_p1, s_data.minptt as minptt_p1, s_data.avgptt as avgptt_p1,
s_data.maxpvco2 as maxpvco2_p1, s_data.minpvco2 as minpvco2_p1, s_data.maxpvo2 as maxpvo2_p1,
s_data.maxpvo2 as maxpvo2_p1, s_data.minpvo2 as minpvo2_p1, s_data.maxpvo2 as maxpvo2_p1,
s_data.maxrbc as maxrbc_p1, s_data.minrbc as minrbc_p1, s_data.avgrbc as avgrbc_p1, 
s_data.maxrdw as maxrdw_p1, s_data.minrdw as minrdw_p1, s_data.avgrdw as avgrdw_p1, 
s_data.maxsvo2_2641 as maxsvo2_2641_p1, s_data.avgsvo2_2641 as avgsvo2_2641_p1, 
s_data.maxsvo2_4351 as maxsvo2_4351_p1, s_data.avgsvo2_4351 as avgsvo2_4351_p1, 
s_data.maxtroponin_old as maxtroponin_old_p1, s_data.avgtroponin_old as avgtroponin_old_p1, 
s_data.maxlactate as maxlactate_p1, s_data.avglactate as avglactate_p1, 

s_data.minenc_eio as minenc_eio_p1, s_data.countenc_eio as countenc_eio_p1,  
s_data.concatdischarge_dispo as concatdischarge_dispo_p1, 
s_data.diffbmi as diffbmi_p1, s_data.avgbmi as avgbmi_p1, 
s_data.mintime_start as mintime_start_p1, s_data.maxtime_start as maxtime_start_p1, 
s_data.mintime_end as mintime_end_p1, s_data.maxtime_end as maxtime_end_p1,
s_data.mintime_adm as mintime_adm_p1, s_data.maxtime_adm as maxtime_adm_p1, 
s_data.mintime_disch as mintime_disch_p1, s_data.maxtime_disch as maxtime_disch_p1, 

s_data.maxadmission_order as maxadmission_order_p1,
s_data.maxct_chestabdpelviswo as maxct_chestabdpelviswo_p1,
s_data.maxct_chesupabd as maxct_chesupabd_p1,
s_data.maxsitter_order as maxsitter_order_p1, 
s_data.maxtranscryo as maxtranscryo_p1,
s_data.maxtransfer_order as maxtransfer_order_p1,
s_data.maxtransffp as maxtransffp_p1,
s_data.maxtransplts as maxtransplts_p1,
s_data.maxtransrbc as maxtransrbc_p1,
s_data.maxtransrbc_eq1 as maxtransrbc_eq1_p1, 
s_data.maxtransrbc_gt1 as maxtransrbc_gt1_p1, 
s_data.concatreason as concatreason_p1,
s_data.maxtreatment_limit as maxtreatment_limit_p1,
s_data.maxdrip_dexmedetomidine as maxdrip_dexmedetomidine_p1, s_data.avgdrip_dexmedetomidine as avgdrip_dexmedetomidine_p1, 
s_data.maxdrip_dobutamine as maxdrip_dobutamine_p1, s_data.avgdrip_dobutamine as avgdrip_dobutamine_p1, 
s_data.maxdrip_dopamine as maxdrip_dopamine_p1, s_data.avgdrip_dopamine as avgdrip_dopamine_p1, 
s_data.maxdrip_fentanyl as maxdrip_fentanyl_p1, s_data.avgdrip_fentanyl as avgdrip_fentanyl_p1, 
s_data.maxdrip_midazolam as maxdrip_midazolam_p1, s_data.avgdrip_midazolam as avgdrip_midazolam_p1, 
s_data.maxdrip_milrinone as maxdrip_milrinone_p1, s_data.avgdrip_milrinone as avgdrip_milrinone_p1, 
s_data.maxdrip_morphine as maxdrip_morphine_p1, s_data.avgdrip_morphine as avgdrip_morphine_p1, 
s_data.maxdrip_norepinephrine as maxdrip_norepinephrine_p1, s_data.avgdrip_norepinephrine as avgdrip_norepinephrine_p1, 
s_data.maxdrip_phenylephrine as maxdrip_phenylephrine_p1, s_data.avgdrip_phenylephrine as avgdrip_phenylephrine_p1, 
s_data.maxdrip_propofol as maxdrip_propofol_p1, s_data.avgdrip_propofol as avgdrip_propofol_p1, 
s_data.maxdrip_vasopressin as maxdrip_vasopressin_p1, s_data.avgdrip_vasopressin as avgdrip_vasopressin_p1, 
s_data.maxpain_scale as maxpain_scale_p1, s_data.avgpain_scale as avgpain_scale_p1, 
s_data.maxdialysis as maxdialysis_p1,
s_data.maxperitoneal as maxperitoneal_p1,
s_data.maxbraden_activity as maxbraden_activity_p1, s_data.minbraden_activity as minbraden_activity_p1, 
s_data.maxbraden_friction as maxbraden_friction_p1, s_data.minbraden_friction as minbraden_friction_p1, 
s_data.maxbraden_mobility as maxbraden_mobility_p1, s_data.minbraden_mobility as minbraden_mobility_p1, 
s_data.maxbraden_moisture as maxbraden_moisture_p1, s_data.minbraden_moisture as minbraden_moisture_p1, 
s_data.minbraden_nutrition as minbraden_nutrition_p1, s_data.maxbraden_nutrition as maxbraden_nutrition_p1,  
s_data.maxbraden_scale as maxbraden_scale_p1, s_data.avgbraden_scale as avgbraden_scale_p1, 
s_data.maxbraden_sensory as maxbraden_sensory_p1, s_data.minbraden_sensory as minbraden_sensory_p1, 
s_data.maxmorse_ambaid as maxmorse_ambaid_p1, s_data.minmorse_ambaid as minmorse_ambaid_p1, 
s_data.maxmorse_dateoffall as maxmorse_dateoffall_p1, s_data.minmorse_dateoffall as minmorse_dateoffall_p1, 
s_data.maxmorse_fallhistory as maxmorse_fallhistory_p1, s_data.minmorse_fallhistory as minmorse_fallhistory_p1, 
s_data.maxmorse_gaittransfer as maxmorse_gaittransfer_p1, s_data.minmorse_gaittransfer as minmorse_gaittransfer_p1, 
s_data.maxmorse_ivdevice as maxmorse_ivdevice_p1, s_data.minmorse_ivdevice as minmorse_ivdevice_p1, 
s_data.maxmorse_mentalstatus as maxmorse_mentalstatus_p1, s_data.minmorse_mentalstatus as minmorse_mentalstatus_p1, 
s_data.maxmorse_score as maxmorse_score_p1, s_data.avgmorse_score as avgmorse_score_p1, 
s_data.maxmorse_secdiag as maxmorse_secdiag_p1, s_data.mindatamorse_secdiag as mindatamorse_secdiag_p1, 
s_data.countcart as countcart_p1, 
s_data.countcart_loc as countcart_loc_p1, s_data.concatcart_loc as concatcart_loc_p1, 
s_data.concatinitialrhythm as concatinitialrhythm_p1, 
s_data.maxrosc as maxrosc_p1,
s_data.maxrrt as maxrrt_p1,
s_data.maxwardorICU as maxwardorICU_p1,
s_data.maxeverwardorICU as maxeverwardorICU_p1, 
s_data.maxtroponin_flag as maxtroponin_flag_p1,
s_data.maxtroponin as maxtroponin_p1, s_data.sumtroponin as sumtroponin_p1, 
s_data.maxtroponin_bin as maxtroponin_bin_p1, s_data.avgtroponin_bin as avgtroponin_bin_p1, 
s_data.maxct_lowextrem_w as maxct_lowextrem_w_p1,
s_data.maxct_lowextrem_wo as maxct_lowextrem_wo_p1,
s_data.maxct_w_contrast as maxct_w_contrast_p1,
s_data.maxct_wo_contrast as maxct_wo_contrast_p1, 
s_data.maxbipap as maxbipap_p1,
s_data.maxcpap as maxcpap_p1,
s_data.maxtrach as maxtrach_p1,
s_data.maxhfnc as maxhfnc_p1,
s_data.maxother_o2device as maxother_o2device_p1, s_data.sumother_o2device as sumother_o2device_p1, 
s_data.maxfio2_finaltest as maxfio2_finaltest_p1, 
s_data.maxfio2_final3 as maxfio2_final3_p1,
s_data.maxsf_ratio as maxsf_ratio_p1, s_data.avgsf_ratio as avgsf_ratio_p1, 
s_data.maxsuction_1hour_trigger as maxsuction_1hour_trigger_p1,
s_data.maxsuction_route_rt as maxsuction_route_rt_p1,
s_data.maxsuction_route2_nur as maxsuction_route2_nur_p1, 
s_data.maxsuction_zzz as maxsuction_zzz_p1, 
s_data.maxruq_ultrasound01 as maxruq_ultrasound01_p1, 
s_data.maxammonia as maxammonia_p1, s_data.avgammonia as avgammonia_p1, 

s_data.concatabdominal_assess as concatabdominal_assess_p1, s_data.countabdominal_assess as countabdominal_assess_p1,  
s_data.mincardiac_rhythm as mincardiac_rhythm_p1, s_data.maxcardiac_rhythm as maxcardiac_rhythm_p1,
s_data.maxlvad as maxlvad_p1, 
s_data.minmed_name as minmed_name_p1, s_data.countmed_name as countmed_name_p1, 
s_data.maxsedative_icu as maxsedative_icu_p1,
s_data.maxvasoactive as maxvasoactive_p1,
s_data.maxinotrope as maxinotrope_p1, 
s_data.maxnebtrt as maxnebtrt_p1,
s_data.maxivbolus as maxivbolus_p1,
s_data.maxivbolus_lr as maxivbolus_lr_p1,
s_data.maxivbolus_nacl as maxivbolus_nacl_p1,
s_data.maxivbolus_alb as maxivbolus_alb_p1,
s_data.maxhypoglycemic_ins as maxhypoglycemic_ins_p1,
s_data.maxlactulose as maxlactulose_p1, 
s_data.maxirb_drug as maxirb_drug_p1,
s_data.maxaed_med as maxaed_med_p1,
s_data.maxvitals_time as maxvitals_time_p1, s_data.minvitals_time as minvitals_time_p1,
s_data.maxfirst_vitals_time as maxfirst_vitals_time_p1, s_data.minfirst_vitals_time as minfirst_vitals_time_p1, 
s_data.maxlast_vitals_time as maxlast_vitals_time_p1, s_data.minlast_vitals_time as minlast_vitals_time_p1, 
s_data.maxexpired as maxexpired_p1, 
s_data.maxdied01 as maxdied01_p1, 
s_data.maxdied_ever as maxdied_ever_p1,
s_data.maxlos as maxlos_p1, s_data.avglos as avglos_p1, 
s_data.maxicd9_477_x as maxicd9_477_x_p1,  
s_data.maxicd9_691_x as maxicd9_691_x_p1, 
s_data.maxicd9_493_x as maxicd9_493_x_p1, 
s_data.maxicd9_995_3 as maxicd9_995_3_p1, 
s_data.maxicd9_558_3 as maxicd9_558_3_p1, 
s_data.maxroute as maxroute_p1, s_data.countroute as countroute_p1, 
s_data.maxsepsis_glucocorticoid as maxsepsis_glucocorticoid_p1,
s_data.maxsepsis_antibiotic as maxsepsis_antibiotic_p1,
s_data.maxencounter_masterdata as maxencounter_masterdata_p1,
s_data.maxinfxnqsofa as maxinfxnqsofa_p1,
s_data.maxlos_total as maxlos_total_p1, s_data.avglos_total as avglos_total_p1, 
s_data.maxage as maxage_p1, 
s_data.maxtemp_c as maxtemp_c_p1, s_data.mintemp_c as mintemp_c_p1, s_data.avgtemp_c as avgtemp_c_p1,
s_data.maxicu_flag as maxicu_flag_p1,
s_data.maxnum_icustays as maxnum_icustays_p1, 
s_data.maxtemp_c_ecart as maxtemp_c_ecart_p1, s_data.mintemp_c_ecart as mintemp_c_ecart_p1, s_data.avgtemp_c_ecart as avgtemp_c_ecart_p1,
s_data.maxpotassium_ecart as maxpotassium_ecart_p1, s_data.avgpotassium_ecart as avgpotassium_ecart_p1, 
s_data.maxecart_score as maxecart_score_p1, s_data.avgecart_score as avgecart_score_p1,
s_data.maxpao2_sofa as maxpao2_sofa_p1, s_data.sumpao2_sofa as sumpao2_sofa_p1, 
s_data.maxfio2_final3_sofa as maxfio2_final3_sofa_p1, s_data.sumfio2_final3_sofa as sumfio2_final3_sofa_p1, 
s_data.maxgcs_score_sofa as maxgcs_score_sofa_p1, s_data.mingcs_score_sofa as mingcs_score_sofa_p1, 
s_data.maxsofa_resp as maxsofa_resp_p1, s_data.minsofa_resp as minsofa_resp_p1, 
s_data.maxsofa_coag as maxsofa_coag_p1, s_data.minsofa_coag as minsofa_coag_p1, 
s_data.maxsofa_bili as maxsofa_bili_p1, s_data.minsofa_bili as minsofa_bili_p1, 
s_data.maxsofa_card as maxsofa_card_p1, s_data.minsofa_card as minsofa_card_p1, 
s_data.maxsofa_gcs as maxsofa_gcs_p1, s_data.minsofa_gcs as minsofa_gcs_p1, 
s_data.maxsofa_cr as maxsofa_cr_p1, s_data.minsofa_cr as minsofa_cr_p1, 
s_data.maxsofa_score as maxsofa_score_p1, s_data.avgsofa_score as avgsofa_score_p1, 
s_data.maxencount_enum as maxencount_enum_p1, s_data.avgencount_enum as avgencount_enum_p1, 
s_data.maxantibiotic_ad as maxantibiotic_ad_p1, 
s_data.maxantiarrhythmic_ad as maxantiarrhythmic_ad_p1, 
s_data.maxanticoag_ad as maxanticoag_ad_p1, 
s_data.maxantipsych_ad as maxantipsych_ad_p1, 
s_data.maxavnodal_ad as maxavnodal_ad_p1, 
s_data.maxdiuretic_ad as maxdiuretic_ad_p1, 
s_data.maxfungal_ad as maxfungal_ad_p1, 
s_data.maxhypogly_ad as maxhypogly_ad_p1, 
s_data.maximmuno_ad as maximmuno_ad_p1,  
s_data.maxsteroid_ad as maxsteroid_ad_p1, 
s_data.maxantiviral_ad as maxantiviral_ad_p1, 
s_data.sumchest_xray as sumchest_xray_p1, 
s_data.sumchestab_w_ct as sumchestab_w_ct_p1, 
s_data.sumchestab_wo_ct as sumchestab_wo_ct_p1, 
s_data.sumheadneck_w_ct as sumheadneck_w_ct_p1, 
s_data.maxcul_blood_ord as maxcul_blood_ord_p1, 
s_data.maxcul_urine_ord as maxcul_urine_ord_p1, 
s_data.maxcul_other_ord as maxcul_other_ord_p1, 
s_data.maxcul_stool_ord as maxcul_stool_ord_p1, 
s_data.sumelix_comorb as sumelix_comorb_p1, s_data.avgelix_comorb as avgelix_comorb_p1, 
s_data.maxurin_cath as maxurin_cath_p1, 
s_data.maxurin_output as maxurin_output_p1, 
s_data.maxmech_ventil as maxmech_ventil_p1, 
s_data.maxbenzo_diaz as maxbenzo_diaz_p1, 
s_data.maxend_of_life as maxend_of_life_p1, 
s_data.maxekg_ecg as maxekg_ecg1, s_data.sumekg_ecg as sumekg_ecg_p1, 
s_data.countcentral_line as countcentral_line_p1, 
s_data.summob_lo as summob_lo_p1, 
s_data.maxage_yr as maxage_yr_p1, 
s_data.avgalbumin_c as avgalbumin_c_p1, s_data.minalbumin_c as minalbumin_c_p1, 
s_data.avgallphos_c as avgallphos_c_p1, 
s_data.avgavpu_c as avgavpu_c_p1,  
s_data.avgbun_c as avgbun_c_p1, 
s_data.avgbun_cr_c as avgbun_cr_c_p1, 
s_data.avgcalcium_c as avgcalcium_c_p1, 
s_data.avgco2_c as avgco2_c_p1, 
s_data.avgcreatinine_c as avgcreatinine_c_p1, 
s_data.avgdbp_c as avgdbp_c_p1,  
s_data.avggluc_ser_c as avggluc_ser_c_p1, 
s_data.avghb_c as avghb_c_p1, 
s_data.avgo2sat_c as avgo2sat_c_p1, 
s_data.avgplatelet_count_c as avgplatelet_count_c_p1, s_data.minplatelet_count_c as minplatelet_count_c_p1, 
s_data.avgppi_c as avgppi_c_p1, 
s_data.avgrr_c as avgrr_c_p1, 
s_data.avgsbp_c as avgsbp_c_p1, 
s_data.avgsgot_c as avgsgot_c_p1, 
s_data.avgsodium_c as avgsodium_c_p1, 
s_data.avgwbc_c as avgwbc_c_p1, s_data.minwbc_c as minwbc_c_p1
FROM sep
LEFT JOIN s_data USING(patient_id)
WHERE sep.maxtime > s_data.mintime AND sep.encounter_id != s_data.encounter_id;
"""

prior1 = pysqldf(f)
prior1.head()

,patient_id,encounter_id,mintime,maxtime,loc_cat,maxIVF_meds,countIVF_meds,maxIVF_volume,avgIVF_volume,maxIV_intake,...,avgo2sat_c_p1,avgplatelet_count_c_p1,minplatelet_count_c_p1,avgppi_c_p1,avgrr_c_p1,avgsbp_c_p1,avgsgot_c_p1,avgsodium_c_p1,avgwbc_c_p1,minwbc_c_p1
0,192535,2263820,04jul2009 07:34:00,23may2009 18:00:00,742,-0.132921,11,None,None,None,...,0.495180,-0.007550,-0.160499,-1.044907,-0.026386,-0.549074,-0.098670,0.265742,-0.294366,-0.294366
1,540882,2266122,11apr2009 00:00:00,14apr2009 12:00:00,66,0.236750,7,None,None,None,...,0.413273,-0.143320,-0.225971,-0.844798,-0.207338,0.185918,-0.096931,0.224262,-0.430244,-0.462978
2,540882,2266122,11apr2009 00:00:00,14apr2009 12:00:00,66,0.236750,7,None,None,None,...,0.127931,0.126411,-0.160499,-0.696786,-0.317248,0.061668,-0.096931,0.164664,-0.288638,-0.503124
3,1412487,2268096,19jan2009 00:00:00,28jan2009 07:56:00,145,0.236750,26,None,None,None,...,0.139976,-0.977960,-1.090199,-0.949245,-0.373523,-0.512085,0.037818,-0.169905,-0.485551,-0.776115
4,1412487,2268096,19jan2009 00:00:00,28jan2009 07:56:00,145,0.236750,26,None,None,None,...,-0.089961,-0.851432,-1.011633,-0.603614,-0.150283,0.246875,-0.090639,-0.097304,-0.654398,-0.800202

In [6]:
prior1[['patient_id', 'encounter_id', 'encounter_id_p1', 'mintime', 'maxtime', 'mintime_p1', 'maxtime_p1']]

,patient_id,encounter_id,encounter_id_p1,mintime,maxtime,mintime_p1,maxtime_p1
0,192535,2263820,2504372,04jul2009 07:34:00,23may2009 18:00:00,09jul2009 00:00:00,15jul2009 07:47:00
1,540882,2266122,2556915,11apr2009 00:00:00,14apr2009 12:00:00,13jun2009 00:00:00,19jun2009 16:00:00
2,540882,2266122,2594551,11apr2009 00:00:00,14apr2009 12:00:00,09jul2009 07:51:00,23may2009 12:00:00
3,1412487,2268096,2361402,19jan2009 00:00:00,28jan2009 07:56:00,16mar2009 00:00:00,23mar2009 12:30:00
4,1412487,2268096,2364347,19jan2009 00:00:00,28jan2009 07:56:00,22apr2009 00:00:00,25apr2009 14:21:00
5,23130,2269045,2313651,01oct2009 18:30:00,30jul2009 07:31:00,01aug2009 00:00:00,31jul2009 21:00:00
6,1870371,2269672,2304954,02mar2009 00:00:00,08mar2009 08:13:00,07mar2009 00:00:00,10mar2009 11:55:00
7,142116,2292231,2309187,07jun2009 18:38:00,24jan2009 17:00:00,14jun2009 00:00:00,22jun2009 09:36:00
8,72716,2304041,2325650,05mar2009 07:12:00,16mar2009 09:43:00,16jan2009 05:22:00,22jan2009 07:46:00
9,1304107,2305755,2633469,12apr2009 00:00:00,18apr2009 07:07:00,01jul2009 00:00:00,31may2009 23:00:00
10,682096,2312627,2269671,14mar2009 00:00:00,20mar2009 08:25:00,09may2009 00:00:00,10may2009 17:00:00
11,438145,2312808,2530717,01apr2009 00:00:00,31mar2009 23:00:00,15apr2009 00:00:00,25apr2009 16:22:00
12,1452770,2313577,2324082,11dec2009 14:54:00,21jan2010 07:28:00,04dec2009 00:00:00,10dec2009 13:16:00
13,23130,2313651,2269045,01aug2009 00:00:00,31jul2009 21:00:00,01oct2009 18:30:00,30jul2009 07:31:00
14,1432092,2314284,2350742,07jun2009 00:00:00,24jun2009 14:45:00,13mar2009 16:40:00,20mar2009 18:00:00
15,957109,2319372,2360505,01may2009 07:53:00,30apr2009 13:06:00,04mar2009 13:51:00,16mar2009 18:00:00
16,1479091,2319642,2366530,01may2009 00:00:00,30apr2009 23:00:00,05apr2009 10:49:00,12apr2009 07:19:00
17,367125,2323943,2329261,11dec2009 00:00:00,18dec2009 09:11:00,03jan2010 00:00:00,29mar2010 13:23:00
18,72716,2325650,2304041,16jan2009 05:22:00,22jan2009 07:46:00,05mar2009 07:12:00,16mar2009 09:43:00
19,1499278,2328349,2353503,01dec2009 13:04:00,13dec2009 15:31:00,12dec2009 00:09:00,29dec2009 12:45:00
20,367125,2329261,2323943,03jan2010 00:00:00,29mar2010 13:23:00,11dec2009 00:00:00,18dec2009 09:11:00
21,1499278,2353503,2328349,12dec2009 00:09:00,29dec2009 12:45:00,01dec2009 13:04:00,13dec2009 15:31:00
22,1924431,2359566,2317654,05mar2009 07:51:00,28feb2009 14:30:00,11dec2008 10:01:00,17dec2008 07:56:00
23,15765,2360133,2365036,05aug2009 14:04:00,31jul2009 11:26:00,24jul2009 15:04:00,30jul2009 07:56:00
24,957109,2360505,2319372,04mar2009 13:51:00,16mar2009 18:00:00,01may2009 07:53:00,30apr2009 13:06:00
25,1412487,2361402,2268096,16mar2009 00:00:00,23mar2009 12:30:00,19jan2009 00:00:00,28jan2009 07:56:00
26,1412487,2361402,2364347,16mar2009 00:00:00,23mar2009 12:30:00,22apr2009 00:00:00,25apr2009 14:21:00
27,15765,2365036,2360133,24jul2009 15:04:00,30jul2009 07:56:00,05aug2009 14:04:00,31jul2009 11:26:00
28,1479091,2366530,2319642,05apr2009 10:49:00,12apr2009 07:19:00,01may2009 00:00:00,30apr2009 23:00:00
29,1035553,2420316,2543734,07feb2009 07:49:00,23dec2008 07:15:00,02mar2009 07:46:00,28feb2009 07:49:00
...,...,...,...,...,...,...,...
41,1873276,2533552,2538463,01apr2009 00:00:00,31mar2009 23:43:00,17feb2009 00:00:00,19feb2009 13:00:00
42,361230,2540476,2378991,02mar2009 00:00:00,20mar2009 09:14:00,03mar2009 05:46:00,25feb2009 09:25:00
43,1035553,2543734,2420316,02mar2009 07:46:00,28feb2009 07:49:00,07feb2009 07:49:00,23dec2008 07:15:00
44,1035553,2543734,2544565,02mar2009 07:46:00,28feb2009 07:49:00,06jan2009 00:00:00,08jan2009 13:00:00
45,1157466,2544297,2573434,01sep2009 00:00:00,31aug2009 23:53:00,01jul2009 00:10:00,30jun2009 23:35:00
46,1157466,2544297,2578547,01sep2009 00:00:00,31aug2009 23:53:00,09aug2009 00:00:00,17aug2009 10:07:00
47,147928,2548187,2561058,01apr2010 00:00:00,15apr2010 16:00:00,03dec2009 00:00:00,17dec2009 07:44:00
48,147928,2548187,2614666,01apr2010 00:00:00,15apr2010 16:00:00,02mar2010 07:19:00,28feb2010 07:43:00
49,152378,2550586,2324203,22jan2009 00:00:00,29jan2009 07:42:00,02feb2009 00:00:00,11apr2009 08:41:00
50,1132671,2558472,2617864,01jan2010 00:06:00,31dec2009 23:56:00,14dec2009 00:00:00,24dec2009 06:34:00
51,147928,2561058,2548187,03dec2009 00:00:00,17dec2009 07:44:00,01apr2010 00:00:00,15apr2010 16:00:00
52,147928,2561058,2614666,03dec2009 00:00:00,17dec2009 07:44:00,02mar2010 07:19:00,28feb2010 07:43:00
53,1157466,2573434,2544297,01jul2009 00:10:00,30jun2009 23:35:00,01sep2009 00:00:00,31aug2009 23:53:00
54,1157466,2573434,2578547,01jul2009 00:10:00,30jun2009 23:35:00,09aug2009 00:00:00,17aug2009 10:07:00
55,171540,2576881,2579545,10jul2009 00:00:00,16jul2009 07:26:00,11aug2009 00:00:00,15aug2009 08:22:00
56,1157466,2578547,2544297,09aug2009 00:00:00,17aug2009 10:07:00,01sep2009 00:00:00,31aug2009 23:53:00
57,1157466,2578547,2573434,09aug2009 00:00:00,17aug2009 10:07:00,01jul2009 00:10:00,30jun2009 23:35:00
58,171540,2579545,2576881,11aug2009 00:00:00,15aug2009 08:22:00,10jul2009 00:00:00,16jul2009 07:26:00
59,540882,2594551,2266122,09jul2009 07:51:00,23may2009 12:00:00,11apr2009 00:00:00,14apr2009 12:00:00
60,540882,2594551,2556915,09jul2009 07:51:00,23may2009 12:00:00,13jun2009 00:00:00,19jun2009 16:00:00
61,31179,2604275,2328799,01sep2009 00:00:00,31aug2009 21:00:00,19aug2009 00:00:00,24aug2009 11:00:00
62,60770,2608741,2618648,09nov2009 00:00:00,24nov2009 07:05:00,02jan2010 14:19:00,04jan2010 15:06:00
63,79762,2613734,2509686,23jan2010 00:00:00,29jan2010 07:45:00,15feb2010 00:00:00,22feb2010 07:06:00
64,147928,2614666,2548187,02mar2010 07:19:00,28feb2010 07:43:00,01apr2010 00:00:00,15apr2010 16:00:00
65,147928,2614666,2561058,02mar2010 07:19:00,28feb2010 07:43:00,03dec2009 00:00:00,17dec2009 07:44:00
66,621595,2619518,2506340,01jan2010 00:03:00,31dec2009 00:00:00,06nov2009 00:00:00,08nov2009 15:18:00
67,104409,2628428,2652751,05sep2009 18:24:00,31may2009 13:12:00,10may2009 00:00:00,14may2009 15:26:00
68,1304107,2633469,2305755,01jul2009 00:00:00,31may2009 23:00:00,12apr2009 00:00:00,18apr2009 07:07:00
69,1405540,2658992,2559179,03dec2009 00:00:00,10dec2009 07:20:00,07jan2010 00:00:00,15jan2010 12:00:00
70,72671,2667646,2611657,03nov2009 00:00:00,27nov2009 11:00:00,26jan2010 00:00:00,29jan2010 15:55:00

In [7]:
g  = """
SELECT prior1.*, 
s_data.encounter_id as encounter_id_p2, 
s_data.mintime as mintime_p2, s_data.maxtime as maxtime_p2, 
s_data.loc_cat as loc_cat_p2, 
s_data.maxIVF_meds as maxIVF_meds_p2, s_data.countIVF_meds as countIVF_meds_p2, 
s_data.maxIVF_volume as maxIVF_volume_p2, s_data.avgIVF_volume as avgIVF_volume_p2, 
s_data.maxIV_intake as maxIV_intake_p2,
s_data.maxfio2 as maxfio2_p2, s_data.avgfio2 as avgfio2_p2, 
s_data.maxfio2_vent as maxfio2_vent2, s_data.avgfio2_vent as avgfio2_vent_p2, 
s_data.maxgastric_output as maxgastric_output_p2, s_data.mingastric_output as mingastric_output_p2, s_data.avggastric_output as avggastric_output_p2, 
s_data.maxgcs_eye as maxgcs_eye_p2, s_data.mingcs_eye as mingcs_eye_p2, 
s_data.maxgcs_motor as maxgcs_motor_p2, s_data.mingcs_motor as mingcs_motor_p2, 
s_data.maxgcs_score as maxgcs_score_p2, s_data.avggcs_score as avggcs_score_p2, 
s_data.maxgcs_verbal as maxgcs_verbal_p2, s_data.mingcs_verbal as mingcs_verbal_p2, 
s_data.maxhfo_fio2 as maxhfo_fio2_p2, s_data.avghfo_fio2 as avghfo_fio2_p2, 
s_data.maxmap_notcalc as maxmap_notcalc_p2, s_data.minmap_notcalc as minmap_notcalc_p2, s_data.avgmap_notcalc as avgmap_notcalc_p2, 
s_data.maxmap_zzz as maxmap_zzz_p2, s_data.minmap_zzz as minmap_zzz_p2, s_data.avgmap_zzz as avgmap_zzz_p2, 
s_data.maxnasal_cannula as maxnasal_cannula_p2, 
s_data.maxni_fio2 as maxni_fio2_p2, s_data.avgni_fio2 as avgni_fio2_p2, 
s_data.maxni_vent as maxni_vent_p2, 
s_data.maxo2_device as maxo2_device_p2, 
s_data.maxo2_flow as maxo2_flow_p2, s_data.mino2_flow as mino2_flow_p2, s_data.avgo2_flow as avgo2_flow_p2, 
s_data.maxrass as maxrass_p2, s_data.minrass as minrass2, s_data.avgrass as avgrass_p2, 
s_data.maxroomair as maxroomair_p2, 
s_data.mintemp as mintemp_p2, s_data.maxtemp as maxtemp_p2, 
s_data.maxtube_output as maxtube_output_p2, s_data.avgtube_output as avgtube_output_p2, 
s_data.maxwound_output as maxwound_output_p2, s_data.avgwound_output as avgwound_output_p2, 
s_data.maxfio2_final as maxfio2_final_p2, 
s_data.maxfio2_final2 as maxfio2_final2_p2, 
s_data.maxsf_ratio_old as maxsf_ratio_old_p2, s_data.avgsf_ratio_old as avgsf_ratio_old_p2, 
s_data.maxcontam_true as maxcontam_true_p2, 
s_data.maxstaph as maxstaph_p2, 
s_data.maxabs_bands as maxabs_bands_p2, s_data.minabs_bands as minabs_bands_p2, s_data.avgabs_bands as avgabs_bands_p2, 
s_data.maxabs_neutrophils as maxabs_neutrophils_p2, s_data.maxabs_neutrophils as maxabs_neutrophil_p2, s_data.avgabs_neutrophils as avgabs_neutrophils_p2, 
s_data.maxalt as maxalt_p2, s_data.minalt as minalt_p2, s_data.avgalt as avgalt_p2, 
s_data.maxantitrypsin as maxantitrypsin_p2, s_data.avgantitrypsin as avgantitrypsin_p2, 
s_data.maxauto_abs_neutrophils as maxauto_abs_neutrophils_p2, s_data.minauto_abs_neutrophils as minauto_abs_neutrophils_p2, 
s_data.maxbands as maxbands_p2, s_data.minbands as minbands_p2, s_data.avgbands as avgbands_p2, 
s_data.maxbasophils as maxbasophils_p2, s_data.minbasophils as minbasophils_p2, s_data.avgbasophils as avgbasophils_p2, 
s_data.maxblasts as maxblasts_p2, s_data.minblasts as minblasts_p2, s_data.avgblasts as avgblasts_p2, 
s_data.mincdiff as mincdiff_p2, s_data.maxcdiff as maxcdiff_p2, s_data.sumcdiff as sumcdiff_p2, 
s_data.maxchloride as maxchloride_p2, s_data.minchloride as minchloride_p2, s_data.avgchloride as avgchloride_p2, 
s_data.maxcortisol as maxcortisol_p2, s_data.mincortisol as mincortisol_p2, s_data.avgcortisol as avgcortisol_p2, 
s_data.maxcrp as maxcrp_p2, s_data.mincrp as mincrp_p2, s_data.avgcrp as avgcrp_p2, 
s_data.maxcul_cathtip as maxcul_cathtip_p2, 
s_data.maxcul_csf as maxcul_csf_p2, 
s_data.maxcul_influenza as maxcul_influenza_p2, 
s_data.maxcul_mrsa as maxcul_mrsa_p2, 
s_data.maxcul_parainfluenza as maxcul_parainfluenza_p2, 
s_data.maxcul_resp as maxcul_resp_p2, 
s_data.maxeosinophils as maxeosinophils_p2, s_data.avgeosinophils as avgeosinophils_p2, 
s_data.maxesr as maxesr_p2, s_data.avgesr as avgesr_p2, 
s_data.maxhb1198 as maxhb1198_p2, s_data.avghb1198 as avghb1198_p2, 
s_data.maxhb1200 as maxhb1200_p2, s_data.avghb1200 as avghb1200_p2, 
s_data.maxhc03 as maxhc03_p2, 
s_data.maxhc03_ven as maxhc03_ven_p2, s_data.avghc03_ven as avghc03_ven_p2, 
s_data.maxhco3_art as maxhco3_art_p2, 
s_data.maxhematocrit as maxhematocrit_p2, s_data.minhematocrit as minhematocrit_p2, s_data.avghematocrit as avghematocrit_p2, 
s_data.maxinr as maxinr_p2, s_data.avginr as avginr_p2, 
s_data.maxketones as maxketones_p2, s_data.minketones as minketones_p2, s_data.avgketones as avgketones_p2, 
s_data.maxlactate1 as maxlactate1_p2, s_data.avglactate1 as avglactate1_p2, 
s_data.maxlactate_wholebld1434 as maxlactate_wholebld1434_p2, s_data.avglactate_wholebld1434 as avglactate_wholebld1434_p2, 
s_data.maxlactate_wholebld4303 as maxlactate_wholebld4303_p2, s_data.avglactate_wholebld4303 as avglactate_wholebld4303_p2, 
s_data.maxlactic_acid as maxlactic_acid_p2, s_data.minlactic_acid as minlactic_acid_p2, s_data.avglactic_acid as avglactic_acid_p2, 
s_data.maxlipase as maxlipase_p2, s_data.minlipase as minlipase_p2, s_data.lipase as avglipase_p2, 
s_data.maxlymphocytes as maxlymphocytes_p2, s_data.minlymphocytes as minlymphocytes_p2, s_data.avglymphocytes as avglymphocytes_p2, 
s_data.maxmagnesium as maxmagnesium_p2, s_data.minmagnesium as minmagnesium_p2, s_data.avgmagnesium as avgmagnesium_p2, 
s_data.maxmcv as maxmcv_p2, s_data.avgmcv as avgmcv_p2, 
s_data.maxmetamyelocytes as maxmetamyelocytes_p2, s_data.minmetamyelocytes as minmetamyelocytes_p2, s_data.avgmetamyelocytes as avgmetamyelocytes_p2, 
s_data.maxmonocytes as maxmonocytes_p2, s_data.minmonocytes as minmonocytes_p2, s_data.avgmonocytes as avgmonocytes_p2, 
s_data.maxneutrophils as maxneutrophils_p2, s_data.minneutrophils as minneutrophils_p2, s_data.avgneutrophils as avgneutrophils_p2, 
s_data.maxnrbc as maxnrbc_p2, s_data.avgnrbc as avgnrbc_p2, 
s_data.maxosmolality as maxosmolality_p2, s_data.minosmolality as minosmolality_p2, s_data.avgosmolality as avgosmolality_p2, 
s_data.maxpaco2 as maxpaco2_p2, s_data.avgpaco2 as avgpaco2_p2, 
s_data.maxpao2 as maxpao2_p2, s_data.avgpao2 as avgpao2_p2, 
s_data.maxpco2_1097 as maxpco2_1097_p2, 
s_data.maxpco2_4098 as maxpco2_4098_p2, 
s_data.maxph1250 as maxph1250_p2, s_data.avgph1250 as avgph1250_p2, 
s_data.maxph1819 as maxph1819_p2, s_data.avgph1819 as avgph1819_p2, 
s_data.maxph272 as maxph272_p2, s_data.avgph272 as avgph272_p2, 
s_data.maxph4315 as maxph4315_p2, s_data.avgph4315 as avgph4315_p2, 
s_data.maxph690 as maxph690_p2, s_data.avgph690 as avgph690_p2, 
s_data.maxphosphate as maxphosphate_p2, s_data.minphosphate as minphosphate_p2, s_data.avgphosphate as avgphosphate_p2,
s_data.maxpotassium as maxpotassium_p2, s_data.minpotassium as minpotassium_p2, s_data.avgpotassium as avgpotassium_p2, 
s_data.maxpromyelocytes as maxpromyelocytes_p2, s_data.avgpromyelocytes as avgpromyelocytes_p2, 
s_data.maxtotal_protein as maxtotal_protein_p2, s_data.avgtotal_protein as avgtotal_protein_p2, 
s_data.maxptt as maxptt_p2, s_data.minptt as minptt_p2, s_data.avgptt as avgptt_p2,
s_data.maxpvco2 as maxpvco2_p2, s_data.minpvco2 as minpvco2_p2, s_data.maxpvo2 as maxpvo2_p2,
s_data.maxpvo2 as maxpvo2_p2, s_data.minpvo2 as minpvo2_p2, s_data.maxpvo2 as maxpvo2_p2,
s_data.maxrbc as maxrbc_p2, s_data.minrbc as minrbc_p2, s_data.avgrbc as avgrbc_p2, 
s_data.maxrdw as maxrdw_p2, s_data.minrdw as minrdw_p2, s_data.avgrdw as avgrdw_p2, 
s_data.maxsvo2_2641 as maxsvo2_2641_p2, s_data.avgsvo2_2641 as avgsvo2_2641_p2, 
s_data.maxsvo2_4351 as maxsvo2_4351_p2, s_data.avgsvo2_4351 as avgsvo2_4351_p2, 
s_data.maxtroponin_old as maxtroponin_old_p2, s_data.avgtroponin_old as avgtroponin_old_p2, 
s_data.maxlactate as maxlactate_p2, s_data.avglactate as avglactate_p2, 

s_data.minenc_eio as minenc_eio_p2, s_data.countenc_eio as countenc_eio_p2,  
s_data.concatdischarge_dispo as concatdischarge_dispo_p2, 
s_data.diffbmi as diffbmi_p2, s_data.avgbmi as avgbmi_p2, 
s_data.mintime_start as mintime_start_p2, s_data.maxtime_start as maxtime_start_p2, 
s_data.mintime_end as mintime_end_p2, s_data.maxtime_end as maxtime_end_p2,
s_data.mintime_adm as mintime_adm_p2, s_data.maxtime_adm as maxtime_adm_p2, 
s_data.mintime_disch as mintime_disch_p2, s_data.maxtime_disch as maxtime_disch_p2, 

s_data.maxadmission_order as maxadmission_order_p2,
s_data.maxct_chestabdpelviswo as maxct_chestabdpelviswo_p2,
s_data.maxct_chesupabd as maxct_chesupabd_p2,
s_data.maxsitter_order as maxsitter_order_p2, 
s_data.maxtranscryo as maxtranscryo_p2,
s_data.maxtransfer_order as maxtransfer_order_p2,
s_data.maxtransffp as maxtransffp_p2,
s_data.maxtransplts as maxtransplts_p2,
s_data.maxtransrbc as maxtransrbc_p2,
s_data.maxtransrbc_eq1 as maxtransrbc_eq1_p2, 
s_data.maxtransrbc_gt1 as maxtransrbc_gt1_p2, 
s_data.concatreason as concatreason_p2,
s_data.maxtreatment_limit as maxtreatment_limit_p2,
s_data.maxdrip_dexmedetomidine as maxdrip_dexmedetomidine_p2, s_data.avgdrip_dexmedetomidine as avgdrip_dexmedetomidine_p2, 
s_data.maxdrip_dobutamine as maxdrip_dobutamine_p2, s_data.avgdrip_dobutamine as avgdrip_dobutamine_p2, 
s_data.maxdrip_dopamine as maxdrip_dopamine_p2, s_data.avgdrip_dopamine as avgdrip_dopamine_p2, 
s_data.maxdrip_fentanyl as maxdrip_fentanyl_p2, s_data.avgdrip_fentanyl as avgdrip_fentanyl_p2, 
s_data.maxdrip_midazolam as maxdrip_midazolam_p2, s_data.avgdrip_midazolam as avgdrip_midazolam_p2, 
s_data.maxdrip_milrinone as maxdrip_milrinone_p2, s_data.avgdrip_milrinone as avgdrip_milrinone_p2, 
s_data.maxdrip_morphine as maxdrip_morphine_p2, s_data.avgdrip_morphine as avgdrip_morphine_p2, 
s_data.maxdrip_norepinephrine as maxdrip_norepinephrine_p2, s_data.avgdrip_norepinephrine as avgdrip_norepinephrine_p2, 
s_data.maxdrip_phenylephrine as maxdrip_phenylephrine_p2, s_data.avgdrip_phenylephrine as avgdrip_phenylephrine_p2, 
s_data.maxdrip_propofol as maxdrip_propofol_p2, s_data.avgdrip_propofol as avgdrip_propofol_p2, 
s_data.maxdrip_vasopressin as maxdrip_vasopressin_p2, s_data.avgdrip_vasopressin as avgdrip_vasopressin_p2, 
s_data.maxpain_scale as maxpain_scale_p2, s_data.avgpain_scale as avgpain_scale_p2, 
s_data.maxdialysis as maxdialysis_p2,
s_data.maxperitoneal as maxperitoneal_p2,
s_data.maxbraden_activity as maxbraden_activity_p2, s_data.minbraden_activity as minbraden_activity_p2, 
s_data.maxbraden_friction as maxbraden_friction_p2, s_data.minbraden_friction as minbraden_friction_p2, 
s_data.maxbraden_mobility as maxbraden_mobility_p2, s_data.minbraden_mobility as minbraden_mobility_p2, 
s_data.maxbraden_moisture as maxbraden_moisture_p2, s_data.minbraden_moisture as minbraden_moisture_p2, 
s_data.minbraden_nutrition as minbraden_nutrition_p2, s_data.maxbraden_nutrition as maxbraden_nutrition_p2,  
s_data.maxbraden_scale as maxbraden_scale_p2, s_data.avgbraden_scale as avgbraden_scale_p2, 
s_data.maxbraden_sensory as maxbraden_sensory_p2, s_data.minbraden_sensory as minbraden_sensory_p2, 
s_data.maxmorse_ambaid as maxmorse_ambaid_p2, s_data.minmorse_ambaid as minmorse_ambaid_p2, 
s_data.maxmorse_dateoffall as maxmorse_dateoffall_p2, s_data.minmorse_dateoffall as minmorse_dateoffall_p2, 
s_data.maxmorse_fallhistory as maxmorse_fallhistory_p2, s_data.minmorse_fallhistory as minmorse_fallhistory_p2, 
s_data.maxmorse_gaittransfer as maxmorse_gaittransfer_p2, s_data.minmorse_gaittransfer as minmorse_gaittransfer_p2, 
s_data.maxmorse_ivdevice as maxmorse_ivdevice_p2, s_data.minmorse_ivdevice as minmorse_ivdevice_p2, 
s_data.maxmorse_mentalstatus as maxmorse_mentalstatus_p2, s_data.minmorse_mentalstatus as minmorse_mentalstatus_p2, 
s_data.maxmorse_score as maxmorse_score_p2, s_data.avgmorse_score as avgmorse_score_p2, 
s_data.maxmorse_secdiag as maxmorse_secdiag_p2, s_data.mindatamorse_secdiag as mindatamorse_secdiag_p2, 
s_data.countcart as countcart_p2, 
s_data.countcart_loc as countcart_loc_p2, s_data.concatcart_loc as concatcart_loc_p2, 
s_data.concatinitialrhythm as concatinitialrhythm_p2, 
s_data.maxrosc as maxrosc_p2,
s_data.maxrrt as maxrrt_p2,
s_data.maxwardorICU as maxwardorICU_p2,
s_data.maxeverwardorICU as maxeverwardorICU_p2, 
s_data.maxtroponin_flag as maxtroponin_flag_p2,
s_data.maxtroponin as maxtroponin_p2, s_data.sumtroponin as sumtroponin_p2, 
s_data.maxtroponin_bin as maxtroponin_bin_p2, s_data.avgtroponin_bin as avgtroponin_bin_p2, 
s_data.maxct_lowextrem_w as maxct_lowextrem_w_p2,
s_data.maxct_lowextrem_wo as maxct_lowextrem_wo_p2,
s_data.maxct_w_contrast as maxct_w_contrast_p2,
s_data.maxct_wo_contrast as maxct_wo_contrast_p2, 
s_data.maxbipap as maxbipap_p2,
s_data.maxcpap as maxcpap_p2,
s_data.maxtrach as maxtrach_p2,
s_data.maxhfnc as maxhfnc_p2,
s_data.maxother_o2device as maxother_o2device_p2, s_data.sumother_o2device as sumother_o2device_p2, 
s_data.maxfio2_finaltest as maxfio2_finaltest_p2, 
s_data.maxfio2_final3 as maxfio2_final3_p2,
s_data.maxsf_ratio as maxsf_ratio_p2, s_data.avgsf_ratio as avgsf_ratio_p2, 
s_data.maxsuction_1hour_trigger as maxsuction_1hour_trigger_p2,
s_data.maxsuction_route_rt as maxsuction_route_rt_p2,
s_data.maxsuction_route2_nur as maxsuction_route2_nur_p2, 
s_data.maxsuction_zzz as maxsuction_zzz_p2, 
s_data.maxruq_ultrasound01 as maxruq_ultrasound01_p2, 
s_data.maxammonia as maxammonia_p2, s_data.avgammonia as avgammonia_p2, 

s_data.concatabdominal_assess as concatabdominal_assess_p2, s_data.countabdominal_assess as countabdominal_assess_p2,  
s_data.mincardiac_rhythm as mincardiac_rhythm_p2, s_data.maxcardiac_rhythm as maxcardiac_rhythm_p2,
s_data.maxlvad as maxlvad_p2, 
s_data.minmed_name as minmed_name_p2, s_data.countmed_name as countmed_name_p2, 
s_data.maxsedative_icu as maxsedative_icu_p2,
s_data.maxvasoactive as maxvasoactive_p2,
s_data.maxinotrope as maxinotrope_p2, 
s_data.maxnebtrt as maxnebtrt_p2,
s_data.maxivbolus as maxivbolus_p2,
s_data.maxivbolus_lr as maxivbolus_lr_p2,
s_data.maxivbolus_nacl as maxivbolus_nacl_p2,
s_data.maxivbolus_alb as maxivbolus_alb_p2,
s_data.maxhypoglycemic_ins as maxhypoglycemic_ins_p2,
s_data.maxlactulose as maxlactulose_p2, 
s_data.maxirb_drug as maxirb_drug_p2,
s_data.maxaed_med as maxaed_med_p2,
s_data.maxvitals_time as maxvitals_time_p2, s_data.minvitals_time as minvitals_time_p2,
s_data.maxfirst_vitals_time as maxfirst_vitals_time_p2, s_data.minfirst_vitals_time as minfirst_vitals_time_p2, 
s_data.maxlast_vitals_time as maxlast_vitals_time_p2, s_data.minlast_vitals_time as minlast_vitals_time_p2, 
s_data.maxexpired as maxexpired_p2, 
s_data.maxdied01 as maxdied01_p2, 
s_data.maxdied_ever as maxdied_ever_p2,
s_data.maxlos as maxlos_p2, s_data.avglos as avglos_p2, 
s_data.maxicd9_477_x as maxicd9_477_x_p2,  
s_data.maxicd9_691_x as maxicd9_691_x_p2, 
s_data.maxicd9_493_x as maxicd9_493_x_p2, 
s_data.maxicd9_995_3 as maxicd9_995_3_p2, 
s_data.maxicd9_558_3 as maxicd9_558_3_p2, 
s_data.maxroute as maxroute_p2, s_data.countroute as countroute_p2, 
s_data.maxsepsis_glucocorticoid as maxsepsis_glucocorticoid_p2,
s_data.maxsepsis_antibiotic as maxsepsis_antibiotic_p2,
s_data.maxencounter_masterdata as maxencounter_masterdata_p2,
s_data.maxinfxnqsofa as maxinfxnqsofa_p2,
s_data.maxlos_total as maxlos_total_p2, s_data.avglos_total as avglos_total_p2, 
s_data.maxage as maxage_p2, 
s_data.maxtemp_c as maxtemp_c_p2, s_data.mintemp_c as mintemp_c_p2, s_data.avgtemp_c as avgtemp_c_p2,
s_data.maxicu_flag as maxicu_flag_p2,
s_data.maxnum_icustays as maxnum_icustays_p2, 
s_data.maxtemp_c_ecart as maxtemp_c_ecart_p2, s_data.mintemp_c_ecart as mintemp_c_ecart_p2, s_data.avgtemp_c_ecart as avgtemp_c_ecart_p2,
s_data.maxpotassium_ecart as maxpotassium_ecart_p2, s_data.avgpotassium_ecart as avgpotassium_ecart_p2, 
s_data.maxecart_score as maxecart_score_p2, s_data.avgecart_score as avgecart_score_p2,
s_data.maxpao2_sofa as maxpao2_sofa_p2, s_data.sumpao2_sofa as sumpao2_sofa_p2, 
s_data.maxfio2_final3_sofa as maxfio2_final3_sofa_p2, s_data.sumfio2_final3_sofa as sumfio2_final3_sofa_p2, 
s_data.maxgcs_score_sofa as maxgcs_score_sofa_p2, s_data.mingcs_score_sofa as mingcs_score_sofa_p2, 
s_data.maxsofa_resp as maxsofa_resp_p2, s_data.minsofa_resp as minsofa_resp_p2, 
s_data.maxsofa_coag as maxsofa_coag_p2, s_data.minsofa_coag as minsofa_coag_p2, 
s_data.maxsofa_bili as maxsofa_bili_p2, s_data.minsofa_bili as minsofa_bili_p2, 
s_data.maxsofa_card as maxsofa_card_p2, s_data.minsofa_card as minsofa_card_p2, 
s_data.maxsofa_gcs as maxsofa_gcs_p2, s_data.minsofa_gcs as minsofa_gcs_p2, 
s_data.maxsofa_cr as maxsofa_cr_p2, s_data.minsofa_cr as minsofa_cr_p2, 
s_data.maxsofa_score as maxsofa_score_p2, s_data.avgsofa_score as avgsofa_score_p2, 
s_data.maxencount_enum as maxencount_enum_p2, s_data.avgencount_enum as avgencount_enum_p2, 
s_data.maxantibiotic_ad as maxantibiotic_ad_p2, 
s_data.maxantiarrhythmic_ad as maxantiarrhythmic_ad_p2, 
s_data.maxanticoag_ad as maxanticoag_ad_p2, 
s_data.maxantipsych_ad as maxantipsych_ad_p2, 
s_data.maxavnodal_ad as maxavnodal_ad_p2, 
s_data.maxdiuretic_ad as maxdiuretic_ad_p2, 
s_data.maxfungal_ad as maxfungal_ad_p2, 
s_data.maxhypogly_ad as maxhypogly_ad_p2, 
s_data.maximmuno_ad as maximmuno_ad_p2,  
s_data.maxsteroid_ad as maxsteroid_ad_p2, 
s_data.maxantiviral_ad as maxantiviral_ad_p2, 
s_data.sumchest_xray as sumchest_xray_p2, 
s_data.sumchestab_w_ct as sumchestab_w_ct_p2, 
s_data.sumchestab_wo_ct as sumchestab_wo_ct_p2, 
s_data.sumheadneck_w_ct as sumheadneck_w_ct_p2, 
s_data.maxcul_blood_ord as maxcul_blood_ord_p2, 
s_data.maxcul_urine_ord as maxcul_urine_ord_p2, 
s_data.maxcul_other_ord as maxcul_other_ord_p2, 
s_data.maxcul_stool_ord as maxcul_stool_ord_p2, 
s_data.sumelix_comorb as sumelix_comorb_p2, s_data.avgelix_comorb as avgelix_comorb_p2, 
s_data.maxurin_cath as maxurin_cath_p2, 
s_data.maxurin_output as maxurin_output_p2, 
s_data.maxmech_ventil as maxmech_ventil_p2, 
s_data.maxbenzo_diaz as maxbenzo_diaz_p2, 
s_data.maxend_of_life as maxend_of_life_p2, 
s_data.maxekg_ecg as maxekg_ecg2, s_data.sumekg_ecg as sumekg_ecg_p2, 
s_data.countcentral_line as countcentral_line_p2, 
s_data.summob_lo as summob_lo_p2, 
s_data.maxage_yr as maxage_yr_p2, 
s_data.avgalbumin_c as avgalbumin_c_p2, s_data.minalbumin_c as minalbumin_c_p2, 
s_data.avgallphos_c as avgallphos_c_p2, 
s_data.avgavpu_c as avgavpu_c_p2,  
s_data.avgbun_c as avgbun_c_p2, 
s_data.avgbun_cr_c as avgbun_cr_c_p2, 
s_data.avgcalcium_c as avgcalcium_c_p2, 
s_data.avgco2_c as avgco2_c_p2, 
s_data.avgcreatinine_c as avgcreatinine_c_p2, 
s_data.avgdbp_c as avgdbp_c_p2,  
s_data.avggluc_ser_c as avggluc_ser_c_p2, 
s_data.avghb_c as avghb_c_p2, 
s_data.avgo2sat_c as avgo2sat_c_p2, 
s_data.avgplatelet_count_c as avgplatelet_count_c_p2, s_data.minplatelet_count_c as minplatelet_count_c_p2, 
s_data.avgppi_c as avgppi_c_p2, 
s_data.avgrr_c as avgrr_c_p2, 
s_data.avgsbp_c as avgsbp_c_p2, 
s_data.avgsgot_c as avgsgot_c_p2, 
s_data.avgsodium_c as avgsodium_c_p2, 
s_data.avgwbc_c as avgwbc_c_p2, s_data.minwbc_c as minwbc_c_p2
FROM prior1
LEFT JOIN s_data USING(patient_id)
WHERE prior1.maxtime_p1 > s_data.mintime AND prior1.encounter_id_p1 != s_data.encounter_id;
"""

prior2 = pysqldf(g)
prior2.head()

,patient_id,encounter_id,mintime,maxtime,loc_cat,maxIVF_meds,countIVF_meds,maxIVF_volume,avgIVF_volume,maxIV_intake,...,avgo2sat_c_p2,avgplatelet_count_c_p2,minplatelet_count_c_p2,avgppi_c_p2,avgrr_c_p2,avgsbp_c_p2,avgsgot_c_p2,avgsodium_c_p2,avgwbc_c_p2,minwbc_c_p2
0,192535,2263820,04jul2009 07:34:00,23may2009 18:00:00,742,-0.132921,11,None,None,None,...,0.578715,-0.282637,-0.553330,-0.124248,0.007403,-0.641149,-0.106196,0.436990,-0.383558,-0.559328
1,540882,2266122,11apr2009 00:00:00,14apr2009 12:00:00,66,0.236750,7,None,None,None,...,0.014772,-0.089050,-0.160499,-0.611384,-0.256718,-0.276129,-0.098552,-0.122880,0.006553,-0.438891
2,540882,2266122,11apr2009 00:00:00,14apr2009 12:00:00,66,0.236750,7,None,None,None,...,0.127931,0.126411,-0.160499,-0.696786,-0.317248,0.061668,-0.096931,0.164664,-0.288638,-0.503124
3,540882,2266122,11apr2009 00:00:00,14apr2009 12:00:00,66,0.236750,7,None,None,None,...,0.014772,-0.089050,-0.160499,-0.611384,-0.256718,-0.276129,-0.098552,-0.122880,0.006553,-0.438891
4,540882,2266122,11apr2009 00:00:00,14apr2009 12:00:00,66,0.236750,7,None,None,None,...,0.413273,-0.143320,-0.225971,-0.844798,-0.207338,0.185918,-0.096931,0.224262,-0.430244,-0.462978

In [8]:
#error too many varaibles look up sqlite variable limit

In [9]:
prior2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Columns: 1340 entries, patient_id to minwbc_c_p2
dtypes: float64(1051), int64(49), object(240)
memory usage: 921.3+ KB

In [10]:
frames = [sep, prior1, prior2]
priorconcat = pd.concat(frames, axis=1)

In [11]:
priorconcat.to_csv('priorconcat.csv')

In [12]:
priorconcat.head()

,patient_id,encounter_id,mintime,maxtime,loc_cat,maxIVF_meds,countIVF_meds,maxIVF_volume,avgIVF_volume,maxIV_intake,...,avgo2sat_c_p2,avgplatelet_count_c_p2,minplatelet_count_c_p2,avgppi_c_p2,avgrr_c_p2,avgsbp_c_p2,avgsgot_c_p2,avgsodium_c_p2,avgwbc_c_p2,minwbc_c_p2
0,1437648,1867781,12mar2009 00:00:00,18mar2009 06:41:00,88,0.236750,7,None,None,None,...,0.578715,-0.282637,-0.553330,-0.124248,0.007403,-0.641149,-0.106196,0.436990,-0.383558,-0.559328
1,50126,2114809,07jul2009 00:00:00,19jul2009 14:00:00,480,0.236750,32,None,None,None,...,0.014772,-0.089050,-0.160499,-0.611384,-0.256718,-0.276129,-0.098552,-0.122880,0.006553,-0.438891
2,1920183,2114950,09feb2009 04:35:00,15feb2009 07:15:00,56,NaN,0,None,None,None,...,0.127931,0.126411,-0.160499,-0.696786,-0.317248,0.061668,-0.096931,0.164664,-0.288638,-0.503124
3,264754,2138366,04jul2009 00:00:00,29aug2009 07:45:00,31,-0.132921,1,None,None,None,...,0.014772,-0.089050,-0.160499,-0.611384,-0.256718,-0.276129,-0.098552,-0.122880,0.006553,-0.438891
4,1388201,2154078,03sep2009 00:00:00,12sep2009 08:06:00,153,0.236750,7,None,None,None,...,0.413273,-0.143320,-0.225971,-0.844798,-0.207338,0.185918,-0.096931,0.224262,-0.430244,-0.462978

In [13]:
prior1.to_csv('prior1.csv')
prior2.to_csv('prior2.csv')

In [14]:
sep.to_csv('sep.csv')

In [15]:
priorconcat.describe()

,patient_id,encounter_id,loc_cat,maxIVF_meds,countIVF_meds,maxfio2,avgfio2,maxfio2_vent,avgfio2_vent,maxgastric_output,...,avgo2sat_c_p2,avgplatelet_count_c_p2,minplatelet_count_c_p2,avgppi_c_p2,avgrr_c_p2,avgsbp_c_p2,avgsgot_c_p2,avgsodium_c_p2,avgwbc_c_p2,minwbc_c_p2
count,3.730000e+02,3.730000e+02,373.000000,279.000000,373.000000,67.000000,67.000000,42.000000,42.000000,53.000000,...,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000
mean,9.642788e+05,2.400243e+06,275.879357,0.569337,24.410188,0.970918,-0.067037,2.348682,0.028897,0.695082,...,0.125390,0.024965,-0.443367,-0.059062,-0.155587,0.205303,-0.086526,0.040790,-0.281520,-0.520824
std,6.383691e+05,1.319164e+05,419.887170,5.628492,54.865923,1.438968,1.083104,4.650366,0.530095,1.960963,...,0.347784,0.634003,0.367131,0.658532,0.442973,0.669639,0.048060,0.514579,0.243469,0.159774
min,4.158000e+03,1.867781e+06,21.000000,-0.179130,0.000000,-2.542111,-2.542111,-0.529265,-0.529265,-0.558878,...,-1.018080,-1.342134,-1.496124,-1.086285,-0.938094,-1.501580,-0.125051,-1.512417,-0.697643,-0.896552
25%,3.136920e+05,2.304041e+06,85.000000,-0.040503,0.000000,-0.685318,-0.696900,1.011619,-0.346792,-0.546313,...,-0.111533,-0.325376,-0.571335,-0.606142,-0.429803,-0.263169,-0.112848,-0.171899,-0.461408,-0.603488
50%,1.025117e+06,2.353769e+06,158.000000,0.236750,8.000000,2.246460,-0.384863,1.525247,-0.109802,-0.181931,...,0.122831,0.034093,-0.330726,-0.189035,-0.185412,0.185918,-0.096931,0.021832,-0.329287,-0.551299
75%,1.466868e+06,2.520285e+06,275.000000,0.236750,24.000000,2.246460,0.554167,1.525247,0.243239,0.802319,...,0.394025,0.383695,-0.160499,0.300066,-0.063648,0.653813,-0.090639,0.253388,-0.117617,-0.388708
max,1.929412e+06,2.668016e+06,3429.000000,94.040862,434.000000,2.246460,2.246460,21.727942,1.525247,6.980056,...,0.826274,1.848018,-0.160499,1.483328,1.942122,1.976914,0.120445,1.811794,0.460961,-0.294366

In [16]:
priorconcat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Columns: 2686 entries, patient_id to minwbc_c_p2
dtypes: float64(2212), int64(17), object(457)
memory usage: 7.6+ MB